    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subquick" id="quick">
                    <figure class="subkort">
                        <img class="subquickpic" src="img/quick.jpg" alt="Quick and Dirty video">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Quick and Dirty video</h2>
							<p>Quick and Dirty video. Nej det er ikke x rated. Quick and Dirty kan bruges som et redskab til at kommunikere et budskab.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
							<p>Det er video der er lavet hurtigt uden de store budgetter inblandet i produktionen af dem. Indeholdet kan være alt muligt der giver mening at få kommunikeret ud til følgere af en virksomhed, blog eller hvad det nu er der skal skabes opmærksomhed omkring.</p>
							<p>Vi havde en opgave hvor vi skulle lave en Quick and Dirty video, udgangspunktet skulle være en informationsvideo til et produkt eller en service. Varigheden af den færdige video skulle være1½-2½ minut</p>
                            <p>Denne dag havde vi besøg af studerende fra en anden skole som deltog i undervisningen og også skulle være aktive deltagere ved produktionen af vores lille video.</p>
                            <h3>Pre produktion</h3>
                            <p>Der var afsat 2½ time, på den tid skulle findes et emne, tege stilleing til hvorvidt der skulle være musik eller en fortæller. Der skulle også laves en shot list, så der var en plan for hvad der skulle optages og hvor optagelsen skulle finde sted. Et egentligt storyboard, var ikke et krav.</p>
                            <h3>Produktion</h3>
                            <p>Her var der 1½ time til at få filmet det der var på shot listen, der var selvfølgelig udstyr til rådighed, så der både kunne sættes lys og laves ordentlig lyd.</p>
                            <h3>Post produktion</h3>
                            <p>Vi havde nu en 1 time til at redigere og uploade vores Quick and Dirty video. Det blev lidt en udfordring idet vi blev anbefalet et bruge et redigeringsprogram som ingen af os havde kendskab til, og som desværre havde det med at gå i baglås ind imellem.</p>
                            <p>Selvom det næppe rækker til en Oscar, så kom vi frem til et færdigt resultat. Det kan ses herunder.</p>
                            
                            <p><video preload="none" src="http://gert3987.web.eadania.dk/eksamen/img/covfeefee.mp4" width="320" height="240" controls="controls">
                            Din browser understøtter desværre ikke denne video.
                            </p></video>

                            <p>Som det ses og ikke mindst høres, var redigeringsprocessen ikke optimal, men der var i dette tilfælde ikke tiden til at lave yderligere rettelser.</p>                     
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Quick and Dirty video</h2>
							<p>Quick and Dirty video. Nej det er ikke x rated. Quick and Dirty kan bruges som et redskab til at kommunikere et budskab.</p>
							<p>Det er video der er lavet hurtigt uden de store budgetter inblandet i produktionen af dem. Indeholdet kan være alt muligt der giver mening at få kommunikeret ud til følgere af en virksomhed, blog eller hvad det nu er der skal skabes opmærksomhed omkring.</p>
							<p>Vi havde en opgave hvor vi skulle lave en Quick and Dirty video, udgangspunktet skulle være en informationsvideo til et produkt eller en service. Varigheden af den færdige video skulle være1½-2½ minut</p>
                            <p>Denne dag havde vi besøg af studerende fra en anden skole som deltog i undervisningen og også skulle være aktive deltagere ved produktionen af vores lille video.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <h3>Pre produktion</h3>
                            <p>Der var afsat 2½ time, på den tid skulle findes et emne, tege stilleing til hvorvidt der skulle være musik eller en fortæller. Der skulle også laves en shot list, så der var en plan for hvad der skulle optages og hvor optagelsen skulle finde sted. Et egentligt storyboard, var ikke et krav.</p>
                            <h3>Produktion</h3>
                            <p>Her var der 1½ time til at få filmet det der var på shot listen, der var selvfølgelig udstyr til rådighed, så der både kunne sættes lys og laves ordentlig lyd.</p>
                            <h3>Post produktion</h3>
                            <p>Vi havde nu en 1 time til at redigere og uploade vores Quick and Dirty video. Det blev lidt en udfordring idet vi blev anbefalet et bruge et redigeringsprogram som ingen af os havde kendskab til, og som desværre havde det med at gå i baglås ind imellem.</p>
                            <p>Selvom det næppe rækker til en Oscar, så kom vi frem til et færdigt resultat. Det kan ses herunder.</p>
                            
                            <p><video preload="none" src="http://gert3987.web.eadania.dk/eksamen/img/covfeefee.mp4" width="320" height="240" controls="controls">
                            Din browser understøtter desværre ikke denne video.
                            </p></video>

                            <p>Som det ses og ikke mindst høres, var redigeringsprocessen ikke optimal, men der var i dette tilfælde ikke tiden til at lave yderligere rettelser.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subvirk" id="virk">
                    <figure class="subkort">
                        <img class="subvirkpic" src="img/grundfos-sinful.png" alt="Virksomhedsbesøg - Sinful og Grundfos">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Virksomhedsbesøg</h2>
                            <p>Besøg hos Sinful i Århus og Grundfos i Bjerringbro.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                        <div class="clearfix">
                            <a target="blank" href="img/sinful.png"> <img class="scalepic30l" src="img/sinful.png" alt="Sinful logo"></a>
                            <p>Ved ankomston til Sinful, blev vi budt velkommen af marketingchef Thomas Jensen.</p>
                            <p>Sinful havde 10 års jubilæum på dagen for vores besøg. Siden starten i en lille lejlighed er Sinful i dag vokset til at være skandinaviens største e-commerce virksomhed med sexlegetøj. De sidste 4 år er virksomheden blevet hædret med Børsens Gazellepris, der gives til vækstvirksomheder. En gazelle er en virksomhed, som i løbet af fire regnskabsår hvert år har haft positiv vækst og samlet set mindst fordoblet omsætningen over de fire år.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </div>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Virksomhedsbesøg</h2>
                            <p>Besøg hos Sinful i Århus og Grundfos i Bjerringbro.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                        <div class="clearfix">
                            <a target="blank" href="img/sinful.png"> <img class="scalepic30l" src="img/sinful.png" alt="Sinful logo"></a>
                            <p>Ved ankomston til Sinful, blev vi budt velkommen af marketingchef Thomas Jensen.</p>
                            <p>Sinful havde 10 års jubilæum på dagen for vores besøg. Siden starten i en lille lejlighed er Sinful i dag vokset til at være skandinaviens største e-commerce virksomhed med sexlegetøj. De sidste 4 år er virksomheden blevet hædret med Børsens Gazellepris, der gives til vækstvirksomheder. En gazelle er en virksomhed, som i løbet af fire regnskabsår hvert år har haft positiv vækst og samlet set mindst fordoblet omsætningen over de fire år.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </div>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
 <!--           <li class="subkort-emne subandet" id="andet">
                    <figure class="subkort">
                        <img class="subandetpic" src="img/andet.png" alt="Alt det andet">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Alt det andet</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Alt det andet</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                    <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>-->
        </ul>
    </main>
