    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subquick" id="quick">
                    <figure class="subkort">
                        <img class="subquickpic" src="img/quick.jpg" alt="Quick and Dirty video">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Quick and Dirty video</h2>
							<p>Quick and Dirty video. Nej det er ikke x rated. Quick and Dirty kan bruges som et redskab til at kommunikere et budskab.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
							<p>Det er video der er lavet hurtigt uden de store budgetter inblandet i produktionen af dem. Indeholdet kan være alt muligt der giver mening at få kommunikeret ud til følgere af en virksomhed, blog eller hvad det nu er der skal skabes opmærksomhed omkring.</p>
							<p>Vi havde en opgave hvor vi skulle lave en Quick and Dirty video, udgangspunktet skulle være en informationsvideo til et produkt eller en service. Varigheden af den færdige video skulle være1½-2½ minut</p>
                            <p>Denne dag havde vi besøg af studerende fra en anden skole som deltog i undervisningen og også skulle være aktive deltagere ved produktionen af vores lille video.</p>
                            <h3>Pre produktion</h3>
                            <p>Der var afsat 2½ time, på den tid skulle findes et emne, tege stilleing til hvorvidt der skulle være musik eller en fortæller. Der skulle også laves en shot list, så der var en plan for hvad der skulle optages og hvor optagelsen skulle finde sted. Et egentligt storyboard, var ikke et krav.</p>
                            <h3>Produktion</h3>
                            <p>Her var der 1½ time til at få filmet det der var på shot listen, der var selvfølgelig udstyr til rådighed, så der både kunne sættes lys og laves ordentlig lyd.</p>
                            <h3>Post produktion</h3>
                            <p>Vi havde nu en 1 time til at redigere og uploade vores Quick and Dirty video. Det blev lidt en udfordring idet vi blev anbefalet et bruge et redigeringsprogram som ingen af os havde kendskab til, og som desværre havde det med at gå i baglås ind imellem.</p>
                            <p>Selvom det næppe rækker til en Oscar, så kom vi frem til et færdigt resultat. Det kan ses herunder.</p>
                            
                            <p><video preload="none" src="http://gert3987.web.eadania.dk/eksamen/img/covfeefee.mp4" width="320" height="240" controls="controls">
                            Din browser understøtter desværre ikke denne video.
                            </p></video>

                            <p>Som det ses og ikke mindst høres, var redigeringsprocessen ikke optimal, men der var i dette tilfælde ikke tiden til at lave yderligere rettelser.</p>                     
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Quick and Dirty video</h2>
							<p>Quick and Dirty video. Nej det er ikke x rated. Quick and Dirty kan bruges som et redskab til at kommunikere et budskab.</p>
							<p>Det er video der er lavet hurtigt uden de store budgetter inblandet i produktionen af dem. Indeholdet kan være alt muligt der giver mening at få kommunikeret ud til følgere af en virksomhed, blog eller hvad det nu er der skal skabes opmærksomhed omkring.</p>
							<p>Vi havde en opgave hvor vi skulle lave en Quick and Dirty video, udgangspunktet skulle være en informationsvideo til et produkt eller en service. Varigheden af den færdige video skulle være1½-2½ minut</p>
                            <p>Denne dag havde vi besøg af studerende fra en anden skole som deltog i undervisningen og også skulle være aktive deltagere ved produktionen af vores lille video.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <h3>Pre produktion</h3>
                            <p>Der var afsat 2½ time, på den tid skulle findes et emne, tege stilleing til hvorvidt der skulle være musik eller en fortæller. Der skulle også laves en shot list, så der var en plan for hvad der skulle optages og hvor optagelsen skulle finde sted. Et egentligt storyboard, var ikke et krav.</p>
                            <h3>Produktion</h3>
                            <p>Her var der 1½ time til at få filmet det der var på shot listen, der var selvfølgelig udstyr til rådighed, så der både kunne sættes lys og laves ordentlig lyd.</p>
                            <h3>Post produktion</h3>
                            <p>Vi havde nu en 1 time til at redigere og uploade vores Quick and Dirty video. Det blev lidt en udfordring idet vi blev anbefalet et bruge et redigeringsprogram som ingen af os havde kendskab til, og som desværre havde det med at gå i baglås ind imellem.</p>
                            <p>Selvom det næppe rækker til en Oscar, så kom vi frem til et færdigt resultat. Det kan ses herunder.</p>
                            
                            <p><video preload="none" src="http://gert3987.web.eadania.dk/eksamen/img/covfeefee.mp4" width="320" height="240" controls="controls">
                            Din browser understøtter desværre ikke denne video.
                            </p></video>

                            <p>Som det ses og ikke mindst høres, var redigeringsprocessen ikke optimal, men der var i dette tilfælde ikke tiden til at lave yderligere rettelser.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subvirk" id="virk">
                    <figure class="subkort">
                        <img class="subvirkpic" src="img/grundfos-sinful.png" alt="Virksomhedsbesøg - Sinful og Grundfos">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Virksomhedsbesøg</h2>
                            <p>Besøg hos Sinful i Århus og Grundfos i Bjerringbro.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                        <div class="clearfix">
                            <a target="blank" href="img/sinful.png"> <img class="scalepic30l" src="img/sinful.png" alt="Sinful logo"></a>
                            <p>Ved ankomston til Sinful, blev vi budt velkommen af marketingchef Thomas Jensen.</p>
                            <p>Sinful havde 10 års jubilæum på dagen for vores besøg. Siden starten i en lille lejlighed er Sinful i dag vokset til at være skandinaviens største e-commerce virksomhed med sexlegetøj. De sidste 4 år er virksomheden blevet hædret med Børsens Gazellepris, der gives til vækstvirksomheder. En gazelle er en virksomhed, som i løbet af fire regnskabsår hvert år har haft positiv vækst og samlet set mindst fordoblet omsætningen over de fire år.</p>
                            <p>Thomas startede med at fortælle lidt om hvem er vi, hvad laver vi, hvor kommer vi fra og hvad laver vi. Det var stort set historien om Sinful fra den spæde start til der hvor virksomheden er i dag, og hvor de ser sig selv fremadrettet. Thomas kom ind på de udfordringer der er for en virksomhed som Sinful i forbindelse med de sociale medier, hvor mange kan reklamere via deres side på f.eks. facebook, er det for Sinful en større udfordring idet der ikke tillades billeder af sexlegetøj, det samme gør sig gældende på mange andre platforme. Sjovt nok kan det godt tillades, såfremt virksomheden betaler sig til en reklame. Moral er godt, dobbelt moral er åbenbart dobbelt så godt.</p>
                            <p>Herefter fortalte han om en af de kampagner der var blevet kørt, Fifty Shades, udsprunget fra filmen Fifty Shades of Gray, der øgede interessen for BDSM, og bragte en meget stor efterspørgsel for legetøj inden for dette univers.</p>
                            <p>Sinful laver deres egne produktbilleder, men video materiale bliver lavet externt.</p>
                            <p>Vi afsluttede med et kort besøg på lageret.</p>
                        </div>
                            
                            
                        <div class="clearfix">
                            <a target="blank" href="img/grundfos.png"> <img class="scalepic30l" src="img/grundfos.png" alt="Grundfos logo"></a>
                            <p>Klokken 13 ankom vi til Grundfos i Bjerringbro, hvor Communication Director Manager Frank B. Winther og communicator Rasmus Reimer Larsen bød velkommen.</p>
                            <p>Efter en kort gannemgang af Grundfos historie blev det taget fat på dagens emne som var brug af video, både i intern og ekstern kommunikation.</p>
                            <p>Vi fik forevist en række eksempler på videoer, der var videoer produceret til sociale medier, til præsentation af løsninger og til intern brug på virksomhedens information skærme.</p>
                            <p>Det var i det hele taget en bred vifte af videoer der blev vist, og vi fik et godt indblik i video kommunikation som et stærkt og brugbart værktøj til at få sit budskab ud.</p>
                            <p>Der blev lagt meget vægt på at Grundfos er mere end blot en virksomhed der skal sælge sine produkter, man ønsker klart et fremstå som en partner der er her for at hjælpe med at finde løsninger til enhver opgave, det uanset om det er i udviklingslande eller til store prestige byggerier i de industrialiserede lande..</p>
                            <p>Frank gjorde også en del ud af at forklare hvori foskellen på arbejdsmetoder når man sammenligner kommunikations afdelingen og marketing afdelingen på Grundfos, hvor marketing er langt flere personer ansat til at gennemføre de enkelte projekter, filmfotografer, tekstforfattere mv. er der i kommunikations afdelingen langt færre ansatte til at udføre opgaverne. Hvor marketing mange gange ofter er fire - fem personer der rejser ud på en opgave, er det for kommunikations afdelingen oftest kun en person, der herved både skal være fotograf, interviewer mm. Derfor stille der også langt større krav til flexibiliteten for en ansat i kommunikations afdelingen, som får et meget bredere arbejdsområde og derofr skal nødvendigvis skal kunne arbejde indefor langt flere områder..</p>
                        </div>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Virksomhedsbesøg</h2>
                            <p>Besøg hos Sinful i Århus og Grundfos i Bjerringbro.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                        <div class="clearfix">
                        <img class="scalepic30l" src="img/sinful.png" alt="Sinful logo"></a>
                            <p>Ved ankomston til Sinful, blev vi budt velkommen af marketingchef Thomas Jensen.</p>
                            <p>Sinful havde 10 års jubilæum på dagen for vores besøg. Siden starten i en lille lejlighed er Sinful i dag vokset til at være skandinaviens største e-commerce virksomhed med sexlegetøj. De sidste 4 år er virksomheden blevet hædret med Børsens Gazellepris, der gives til vækstvirksomheder. En gazelle er en virksomhed, som i løbet af fire regnskabsår hvert år har haft positiv vækst og samlet set mindst fordoblet omsætningen over de fire år.</p>
                            <p>Thomas startede med at fortælle lidt om hvem er vi, hvad laver vi, hvor kommer vi fra og hvad laver vi. Det var stort set historien om Sinful fra den spæde start til der hvor virksomheden er i dag, og hvor de ser sig selv fremadrettet. Thomas kom ind på de udfordringer der er for en virksomhed som Sinful i forbindelse med de sociale medier, hvor mange kan reklamere via deres side på f.eks. facebook, er det for Sinful en større udfordring idet der ikke tillades billeder af sexlegetøj, det samme gør sig gældende på mange andre platforme. Sjovt nok kan det godt tillades, såfremt virksomheden betaler sig til en reklame. Moral er godt, dobbelt moral er åbenbart dobbelt så godt.</p>
                            <p>Herefter fortalte han om en af de kampagner der var blevet kørt, Fifty Shades, udsprunget fra filmen Fifty Shades of Gray, der øgede interessen for BDSM, og bragte en meget stor efterspørgsel for legetøj inden for dette univers.</p>
                            <p>Sinful laver deres egne produktbilleder, men video materiale bliver lavet externt.</p>
                            <p>Vi afsluttede med et kort besøg på lageret.</p>
                        </div>
                        
                        <div class="clearfix">
                        <img class="scalepic30l" src="img/grundfos.png" alt="Grundfos logo"></a>
                            <p>Klokken 13 ankom vi til Grundfos i Bjerringbro, hvor Communication Director Manager Frank B. Winther og communicator Rasmus Reimer Larsen bød velkommen.</p>
                            <p>Efter en kort gannemgang af Grundfos historie blev det taget fat på dagens emne som var brug af video, både i intern og ekstern kommunikation.</p>
                            <p>Vi fik forevist en række eksempler på videoer, der var videoer produceret til sociale medier, til præsentation af løsninger og til intern brug på virksomhedens information skærme.</p>
                            <p>Det var i det hele taget en bred vifte af videoer der blev vist, og vi fik et godt indblik i video kommunikation som et stærkt og brugbart værktøj til at få sit budskab ud.</p>
                            <p>Der blev lagt meget vægt på at Grundfos er mere end blot en virksomhed der skal sælge sine produkter, man ønsker klart et fremstå som en partner der er her for at hjælpe med at finde løsninger til enhver opgave, det uanset om det er i udviklingslande eller til store prestige byggerier i de industrialiserede lande..</p>
                            <p>Frank gjorde også en del ud af at forklare hvori foskellen på arbejdsmetoder når man sammenligner kommunikations afdelingen og marketing afdelingen på Grundfos, hvor marketing er langt flere personer ansat til at gennemføre de enkelte projekter, filmfotografer, tekstforfattere mv. er der i kommunikations afdelingen langt færre ansatte til at udføre opgaverne. Hvor marketing mange gange ofter er fire - fem personer der rejser ud på en opgave, er det for kommunikations afdelingen oftest kun en person, der herved både skal være fotograf, interviewer mm. Derfor stille der også langt større krav til en ansat i kommunikations afdelingen, som får et meget bredere arbejdsområde og derofr skal nødvendigvis skal kunne arbejde indefor langt flere områder.</p>
                        </div>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne submark" id="mark">
                    <figure class="subkort">
                        <img class="submarkpic" src="img/online-marketing.png" alt="Online marketing">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Online marketing</h2>
							<p>Online marketing, et enormt emne som Carsten Guldborg Nielsen forsøgte at give os bare et lille indblik i.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Carsten gennemgik en meget bred vifte af marketing muligheder, selvfølgelig er der alle dem man skal betale for, Google AdWords, reklamer på Facebook og andre sociale medier. Det interessante er dog hvor og hvordan er der mulighed for at få gratis reklame. Det er der bla. ved at arbejde på en god SEO på sin side, herved kommer den højere op i søgeresultater. Det drejer sig i høj grad også om at kende algoritmerne der ligger bag de forskellige sociale medier man færdes på. Det er ikke noget der kommer nemt, der skal arbejdes med det konstant hvis der skal sikres gode placeringer.</p>
                            <p>Det er også af stor betydning hvor god informationsarkitekturen er, for e-commerce virksomheder gælder det i høj grad om at gøre det så nemt som muligt at finde varerne der søges efter, her hjælper det ikke hvis en potientiel kunde søger efter højttaler, nytter det ikke at der bliver vist noget blot fordi der er to t'er i ordet, det er lige så galt hvis der bliver vist for meget, så kan den vare der efterspørges drukne i mængden. Det er derfor nødvendigt at gennemtænke opbygningen og optimere søgefunktioner løbende, så de til alle tider fungere mest hensigtsmæssigt.</p>
                            <p>Nedenstående eksempel viser en søgning efter højttaler, og ikke en af de fremkomne resultater er en højtaler, det er ikke godt nok.</p>
                    <div class="clearfix">
                        <a target="blank" href="img/højtaler.png"> src="img/højtaler.png" alt="Søgning efter højttaler"></a>
                    </div>
                            <p>Et andet sted hvor der mistes meget handel, er ved kassen, alt for mange falder fra netop her, besværlige valg af forsendelse, betalingsmuligheder, CAPTA bekræftelser, køber registrering mv. er med til at kunderne giver op og går andre steder hen. De mange klik for at komme frem til at ordren er afgivet, er ikke noget der gavner i et informationsmiljø hvor tingene går stærkt og tålmodigheden er kort.</p>
                            <p>Ifølge Carstens præsentation falder 70% fra i betalingsprocessen, det er et uhyggeligt tal, hvis der sammenlignes med fysiske butikker, man kan forestille sig et kaos, hvis 70% af kunderne efterlod indkøbsvognen ved kassen, det ville være et omsætningstab der virkelig ville kunne mærkes.</p>
                            <p>Desværre havde jeg ikke mulighed for at være til undervisning andet end et par timer den dag Carsten var og fortælle om Online markedsføring, men jeg var der længe nok til at finde ud af at det er noget der skal arbejdes meget med, såfremt man ønsker at være med helt deroppe hvor det er sjovt.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Online marketing</h2>
							<p>Online marketing, et enormt emne som Carsten Guldborg Nielsen forsøgte at give os bare et lille indblik i.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Carsten gennemgik en meget bred vifte af marketing muligheder, selvfølgelig er der alle dem man skal betale for, Google AdWords, reklamer på Facebook og andre sociale medier. Det interessante er dog hvor og hvordan er der mulighed for at få gratis reklame. Det er der bla. ved at arbejde på en god SEO på sin side, herved kommer den højere op i søgeresultater. Det drejer sig i høj grad også om at kende algoritmerne der ligger bag de forskellige sociale medier man færdes på. Det er ikke noget der kommer nemt, der skal arbejdes med det konstant hvis der skal sikres gode placeringer.</p>
                    <div class="clearfix">
                        <a target="blank" href="img/højtaler.png"> <img class="scalepic30l" src="img/højtaler.png" alt="Søgning efter højttaler"></a>
                            <p>Det er også af stor betydning hvor god informationsarkitekturen er, for e-commerce virksomheder gælder det i høj grad om at gøre det så nemt som muligt at finde varerne der søges efter, her hjælper det ikke hvis en potientiel kunde søger efter højttaler, nytter det ikke at der bliver vist noget blot fordi der er to t'er i ordet, det er lige så galt hvis der bliver vist for meget, så kan den vare der efterspørges drukne i mængden. Det er derfor nødvendigt at gennemtænke opbygningen og optimere søgefunktioner løbende, så de til alle tider fungere mest hensigtsmæssigt.</p>
                            <p>i det indsatte eksempel viser en søgning efter højttaler, og ikke en af de fremkomne resultater er en højtaler, det er ikke godt nok.</p>
                    </div>
                            <p>Et andet sted hvor der mistes meget handel, er ved kassen, alt for mange falder fra netop her, besværlige valg af forsendelse, betalingsmuligheder, CAPTA bekræftelser, køber registrering mv. er med til at kunderne giver op og går andre steder hen. De mange klik for at komme frem til at ordren er afgivet, er ikke noget der gavner i et informationsmiljø hvor tingene går stærkt og tålmodigheden er kort.</p>
                            <p>Ifølge Carstens præsentation falder 70% fra i betalingsprocessen, det er et uhyggeligt tal, hvis der sammenlignes med fysiske butikker, man kan forestille sig et kaos, hvis 70% af kunderne efterlod indkøbsvognen ved kassen, det ville være et omsætningstab der virkelig ville kunne mærkes.</p>
                            <p>Desværre havde jeg ikke mulighed for at være til undervisning andet end et par timer den dag Carsten var og fortælle om Online markedsføring, men jeg var der længe nok til at finde ud af at det er noget der skal arbejdes meget med, såfremt man ønsker at være med helt deroppe hvor det er sjovt.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subdialog" id="dialog">
                    <figure class="subkort">
                        <img class="subdialogpic" src="img/dialog1.jpg" alt="Dialog med håndgribelige genstande">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Dialog med håndgribelige genstande</h2>
                            <p>I forbindelse med Design Thinking havde vi en øvelse hvor vi skulle bruge genstande som en ekstra dimension i vores kommunikation.</p>
                            <p>Der var for hver gruppe udnævnt en facilitator som var den der havde ansvar for tiden, være igangsætter  og sørge for at dialogen omkring de foreslåede emner.
                        </figcaption>
                        
                        <figcaption class="billedtekst2"></p>
                            <p>Der var også til hver gruppe en dokumentarist, hvis opgave det var at få dokumentationen på plads med notater, billeder mv.</p>
							<p>Det var en sjov anderledes måde at kommunikerer på, det viser at kommunikation kan foretages på mange forskellige måder.</p>
							<p>Ideen er at metoden kan bruges i interview situationer i emphathize fasen, det vil i mange tilfælde fremskaffe data som ellers ikke ville komme til udtryk, såfremt der kun blev kommunikeret verbalt.</p>
                            <p>Vi gennemgik hver gruppe to forløb, facilitatoren var fast knyttet til et sted, herved fik hver facilitator mulighed for at drage erfaringer fra den første gruppe, som så kunne bruges til næste.</p>
                            <p>Ved denne øvelse benyttede vi i det ene tilfælde logo klodser, i det andet var det tilfældige genstande i værkstedet der blav anvendt.</p>
                            <p>Det er ikke væsentligt hvad der bruges, det kan i princippet være hvad som helst, ideen er at få frembragt informationer, der ellers ikke ville komme frem.</p>
                    <div class="clearfix">
                        <a target="blank" href="img/dialog2.jpg"> <img class="scalepic50m" src="img/dialog2.jpg" alt="Dialog med håndgribelige genstande"></a>
                    </div>
							<p>Efterfølgende havde vi en dialog i plenum omkring gruppernes oplevelse og forklaring på hvad de nogle af de mange billeder der var blevet taget illustrerede.</p>
                            <p>Efter at have prøvet denne form for kommunikation, er jeg ikke i tvivl om at det vil kunne være et rigtig godt redskab at bruge i givne situationer</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Dialog med håndgribelige genstande</h2>
                            <p>I forbindelse med Design Thinking havde vi en øvelse hvor vi skulle bruge genstande som en  ekstra dimension i vores kommunikation.</p>
                            <p>Der var for hver gruppe udnævnt en facilitator som var den der havde ansvar for tiden, være igangsætter  og sørge for at dialogen omkring de foreslåede emner.
                            <p>Der var også til hver gruppe en dokumentarist, hvis opgave det var at få dokumentationen på plads med notater, billeder mv.</p>
							<p>Det var en sjov anderledes måde at kommunikerer på, det viser at kommunikation kan foretages på mange forskellige måder.</p>
							<p>Ideen er at metoden kan bruges i interview situationer i emphathize fasen, det vil i mange tilfælde fremskaffe data som ellers ikke ville komme til udtryk, såfremt der kun blev kommunikeret verbalt.</p>
                            <p>Vi gennemgik hver gruppe to forløb, facilitatoren var fast knyttet til et sted, herved fik hver facilitator mulighed for at drage erfaringer fra den første gruppe, som så kunne bruges til næste.</p>
                            <p>Ved denne øvelse benyttede vi i det ene tilfælde logo klodser, i det andet var det tilfældige genstande i værkstedet der blav anvendt.</p>
                            <p>Det er ikke væsentligt hvad der bruges, det kan i princippet være hvad som helst, ideen er at få frembragt informationer, der ellers ikke ville komme frem.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                    <div class="clearfix">
                        <a target="blank" href="img/dialog2.jpg"> <img class="scalepic30l" src="img/dialog2.jpg" alt="Dialog med håndgribelige genstande"></a>
							<p>Efterfølgende havde vi en dialog i plenum omkring gruppernes oplevelse og forklaring på hvad de nogle af de mange billeder der var blevet taget illustrerede.</p>
                            <p>Efter at have prøvet denne form for kommunikation, er jeg ikke i tvivl om at det vil kunne være et rigtig godt redskab at bruge i givne situationer</p>
                    </div>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
        </ul>
    </main>
