    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subpsd" id="photoshop">
                    <figure class="subkort">
                        <img class="subpsdpic" src="img/photoshop-logo.png" alt="Adobe Photoshop">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Photoshop</h2>
							<p>Photoshop er et avanceret billedredigeringsprogram.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Programmet har uanede muligheder for efterbehandling og manipulering af billeder. Photoshop arbejder pixel baseret hvilket betyder at alle billeder der hentes ind bliver omdannet til pixels såfremt de ikke allerede er det, dette indebærer at skalering af billeder påvirker billede kvaliteten.</p>
                            <p>Såfremt man vil have mulighed for at skalerer billedet uden kvalitetstab, skal man tilføje en vector mask og gemme billedet i et format til videre behandling i f.eks. Adobe Illustrator.</p>
                            <p>Der arbejdes med layers og layer masks, som gør det muligt at arbejde non destruktivt, man behøver derfor ikke starte helt forfra såfremt der er ting der skal rettes på et senere tidspunkt.</p>
                            <p>Der er i programmet flere muligheder for fritlægning af motiver, og sammensætning af billeder til egne kompositioner.</p>
                            <p>Ved at navngive de enkelte layers, vil man være i stand til hurtigt af finde netop det element man ønsker at arbejde med. Ved brug af selection tools kan der markeres et område af et motiv, som det herefter er muligt at arbejde indenfor uden at påvirke det af motivet der ligger uden for markeringen. Den nemmeste at arbejde med er quick selection tool, idet denne giver mulighed for at flytte sin selection såfremt der er blevet markeret for lidt eller for meget, denne mulighed er ikke tilstede ved de øvrige selection tools der er tilgængelige.</p>
							<p>Programmet giver mulighed for at opsætte interfacet så menuer mv. fremstår forskelligt alt efter hvilke funktioner der lægges vægt på, og hvordan den enkelte bruger finder det mest hensigtsmæssigt.</p>
							<p>Vi har i semesteret blot krattet i overfladen af ganske få af de muligheder som photoshop tilbyder, men man er dog ikke i tvivl om at det er det rette værktøj såfremt der ønskes at arbejde professionelt med redigering/manipulation.</p>
                            <img src="img/outoff.jpg" alt="Outoff frame picture">
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Photoshop</h2>
							<p>Photoshop er et avanceret billedredigeringsprogram.</p>
                            <p>Programmet har uanede muligheder for efterbehandling og manipulering af billeder. Photoshop arbejder pixel baseret hvilket betyder at alle billeder der hentes ind bliver omdannet til pixels såfremt de ikke allerede er det, dette indebærer at skalering af billeder påvirker billede kvaliteten.</p>
                            <p>Såfremt man vil have mulighed for at skalerer billedet uden kvalitetstab, skal man tilføje en vector mask og gemme billedet i et format til videre behandling i f.eks. Adobe Illustrator.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Der arbejdes med layers og layer masks, som gør det muligt at arbejde non destruktivt, man behøver derfor ikke starte helt forfra såfremt der er ting der skal rettes på et senere tidspunkt.</p>
                            <p>Der er i programmet flere muligheder for fritlægning af motiver, og sammensætning af billeder til egne kompositioner.</p>
                            <p>Ved at navngive de enkelte layers, vil man være i stand til hurtigt af finde netop det element man ønsker at arbejde med. Ved brug af selection tools kan der markeres et område af et motiv, som det herefter er muligt at arbejde indenfor uden at påvirke det af motivet der ligger uden for markeringen. Den nemmeste at arbejde med er quick selection tool, idet denne giver mulighed for at flytte sin selection såfremt der er blevet markeret for lidt eller for meget, denne mulighed er ikke tilstede ved de øvrige selection tools der er tilgængelige.</p>
							<p>Programmet giver mulighed for at opsætte interfacet så menuer mv. fremstår forskelligt alt efter hvilke funktioner der lægges vægt på, og hvordan den enkelte bruger finder det mest hensigtsmæssigt.</p>
							<p>Vi har i semesteret blot krattet i overfladen af ganske få af de muligheder som photoshop tilbyder, men man er dog ikke i tvivl om at det er det rette værktøj såfremt der ønskes at arbejde professionelt med redigering/manipulation.</p>
                            <img src="img/outoff.jpg" alt="Outoff frame picture">
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subill" id="illustrator">
                    <figure class="subkort">
                        <img class="subillpic" src="img/illustrator-logo.png" alt="Adobe Illustrator.">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Illustrator</h2>
							<p>Adobe Illustrator er et tegneprogram, her arbejdes med vector grafik.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
                            <p>Dette gør det muligt at skalere emnerne uden tab af kvalitet. Programmet byder på en meget bred vifte af funktioner, vi har i semesteret kun brugt ganske få af disse.</p>
                            <p>Der er mulighed for at tegne i frihånd, men der er også en lang række andre muligheder for tegning af figurer ved hjælp af Shape tool, her kan laves en mængde former og figurer som efterfølgende kan tilpasses som brugeren lyster</p>
							<p>De forskellige figurer kan samles til en sammenhængende enhed, således kan to forskellige figurer blive til en uden det er muligt at se for udenforstående at det ikke er lavet sådan fra starten.</p>
                            <p>I lighed med Adobe Photoshop arbejdes der i Illustrator i layers, således vil man kunne rette i de enkelte layers uden at påvirke de øvrige, igen er der tale om en non destruktiv arbejdsform.</p>
                            <img src="img/badge.png" alt="Badge lavet i Illustrator">
                            <p>Illustrator, er et eminent program til at tegne logoer, det er blot et spørgsmål om, hvor godt den enkelte bruger er inde i programmet.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Illustrator</h2>
							<p>Adobe Illustrator er et tegneprogram, her arbejdes med vector grafik, dette gør det muligt at skalere emnerne uden tab af kvalitet. Programmet byder på en meget bred vifte af funktioner, vi har i semesteret kun brugt ganske få af disse.</p>
                            <p>Der er mulighed for at tegne i frihånd, men der er også en lang række andre muligheder for tegning af figurer ved hjælp af Shape tool, her kan laves en mængde former og figurer som efterfølgende kan tilpasses som brugeren lyster</p>
							<p>De forskellige figurer kan samles til en sammenhængende enhed, således kan to forskellige figurer blive til en uden det er muligt at se for udenforstående at det ikke er lavet sådan fra starten.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>I lighed med Adobe Photoshop arbejdes der i Illustrator i layers, således vil man kunne rette i de enkelte layers uden at påvirke de øvrige, igen er der tale om en non destruktiv arbejdsform.</p>
                            <img src="img/badge.png" alt="Badge lavet i Illustrator">
                            <p>Illustrator, er et eminent program til at tegne logoer, det er blot et spørgsmål om, hvor godt den enkelte bruger er inde i programmet.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
           </li>
            
            <li class="subkort-emne subft" id="farver">
                    <figure class="subkort">
                        <img class="subftpic" src="img/farve.jpg" alt="Farver og typografi.">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Farver og typografi</h2>
							<p>Farver er et vigtigt kommunikationsmiddel, farver er med til at påvirke stemninger, nogle farver giver glæde og positive tanker, andre har det med at lede tankerne i mere dyster retning.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
							<p>Det er dog ikke muligt at give en fast facitliste på hvilke farver der hører til i den ene og den anden kategori, idet kulturelle forskelle har betydning for opfattelsen af farver, ligesom også sammenhængen i hvor de anvendes har betydning.</p>
                            <p>Der arbejdes indenfor to farverum, RGB og CMYK. CMYK / Cyan Magenta Yellow Key(black), er subtraktivt, lys trækkes ud, CMYK lægges ovenpå hinanden og benyttes til tryk og print. RGB bruges på telefoner, computerskærme og TV-apparater. RGB / Red Green Blue, er et additivt system hvor lys tilføjes, modsat CMYK, så bliver RGB farver ikke lagt ovenpå hinanden, men ligger ved siden af hinanden i den enkelte pixel, da en enkelt pixel er så lille kan vores øje ikke skelne de enkelte farver men ser det som en farve.</p>
                            <p>De rene farver betegnes som primær farver, man kan ved opsætning af farvehjulet se hvordan de forskellige farver kan blandes, ved at blande to primær farver får man det der hedder en sekundær farve, tertiære farver opstår nå en primær og en sekundær farve blandes.</p>
                            <img src="img/farvehjul.jpg" alt="Farvehjul">
                            <p>RGB arbejder med væsentligt flere farvenuancer end CMYK, derfor vil et RGB billede der udskrives på en printer ofte ikke have de korrekte farver, det er derfor vigtigt at tage stilling til hvorvidt et billede skal bruges til skærm eller print/tryk.</p>
                            <img src="img/spectrum.jpg" alt="Farvespectrum">
                            <p>Der bruges ved blanding af de forskellige nuancer tre grundbegreber, hue, saturation og brightness. Hue dækker over graduering af kuløren, saturation er farvens mætning (blanding af forskellig mængde gråtone), brightness er lysheden (farven blandes med ren sort elle hvid).</p>
                            <h3>Typografi:</h3>
                            <p>Hvad er typografi? De fleste tænker nok skrifttyper, men typografi er langt mere end det. Skal man sammenfatte det, kan man sige at typografi er den samlede oplevelse af både skrifttype, billeder, kolonner, læsbarhed og layout.</p>
                            <p>De to vigtigste klassifikationer inden for fonte er, serif og sans serif. Serif er kendetegnet med sine fødder, (tynde linjer som afslutter grundstregen). Sans serif har ingen fødder.</p>
                            <p>Typeface udgøres af fontfamilie og weight, tages der udgangspunkt i fontfamilien Arial og tilsættes en weight kan typefaces komme til at se ud som følgende.</p>
                            <img src="img/arial.png" alt="Typeface">
                            <h4>Kilde: Designmagic.com 10 bud om typografi</h4>
                            <h3>Nogle typografiske begreber:</h3>
                            <p class="ital">Minuskler</p>
                            <p>De ‘små’ bogstaver</p>
                            <p class="ital">Majuskler</p>
                            <p>De ‘STORE’ bogstaver. Benævnes også ‘versaler’ eller ‘blokbogstaver’</p>
                            <p class="ital">X-height </p>
                            <p>Er højden på minuskel ‘x’, målt fra bundlinien til toppen af bogstavet. Kan bl.a. benyttes til at parre typefaces.</p>
                            <p class="ital">Leading</p>
                            <p>Bedre kendt som ‘linieafstand’. Måles fra bundlinie til bundlinie. Typisk udregnes leading med 120- 130% af skriftstørrelsen.</p>
                            <p class="ital">Kerning</p>
                            <p>Også kendt som ‘knibning’. Afstanden mellem hvert enkelt bogstav kan justeres, således der skabes balance.</p>
                            <p class="ital">Tracking </p>
                            <p>Justerer den overordnede afstand mellem alle bogstaver i et ord, eller en længere markering af ord.</p>
                            <h4>Kilde: farver og typografi 25/9  v Carsten K Bogner</h4>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Farver og typografi</h2>
							<p>Farver er et vigtigt kommunikationsmiddel, farver er med til at påvirke stemninger, nogle farver giver glæde og positive tanker, andre har det med at lede tankerne i mere dyster retning.</p>
							<p>Det er dog ikke muligt at give en fast facitliste på hvilke farver der hører til i den ene og den anden kategori, idet kulturelle forskelle har betydning for opfattelsen af farver, ligesom også sammenhængen i hvor de anvendes har betydning.</p>
                            <p>Der arbejdes indenfor to farverum, RGB og CMYK. CMYK / Cyan Magenta Yellow Key(black), er subtraktivt, lys trækkes ud, CMYK lægges ovenpå hinanden og benyttes til tryk og print. RGB bruges på telefoner, computerskærme og TV-apparater. RGB / Red Green Blue, er et additivt system hvor lys tilføjes, modsat CMYK, så bliver RGB farver ikke lagt ovenpå hinanden, men ligger ved siden af hinanden i den enkelte pixel, da en enkelt pixel er så lille kan vores øje ikke skelne de enkelte farver men ser det som en farve.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>De rene farver betegnes som primær farver, man kan ved opsætning af farvehjulet se hvordan de forskellige farver kan blandes, ved at blande to primær farver får man det der hedder en sekundær farve, tertiære farver opstår nå en primær og en sekundær farve blandes.</p>
                            <img src="img/farvehjul.jpg" alt="Farvehjul">
                            <p>RGB arbejder med væsentligt flere farvenuancer end CMYK, derfor vil et RGB billede der udskrives på en printer ofte ikke have de korrekte farver, det er derfor vigtigt at tage stilling til hvorvidt et billede skal bruges til skærm eller print/tryk.</p>
                            <img src="img/spectrum.jpg" alt="Farvespectrum">
                            <p>Der bruges ved blanding af de forskellige nuancer tre grundbegreber, hue, saturation og brightness. Hue dækker over graduering af kuløren, saturation er farvens mætning (blanding af forskellig mængde gråtone), brightness er lysheden (farven blandes med ren sort elle hvid).</p>
                            <h3>Typografi:</h3>
                            <p>Hvad er typografi? De fleste tænker nok skrifttyper, men typografi er langt mere end det. Skal man sammenfatte det, kan man sige at typografi er den samlede oplevelse af både skrifttype, billeder, kolonner, læsbarhed og layout.</p>
                            <p>De to vigtigste klassifikationer inden for fonte er, serif og sans serif. Serif er kendetegnet med sine fødder, (tynde linjer som afslutter grundstregen). Sans serif har ingen fødder.</p>
                            <p>Typeface udgøres af fontfamilie og weight, tages der udgangspunkt i fontfamilien Arial og tilsættes en weight kan typefaces komme til at se ud som følgende.</p>
                            <img src="img/arial.png" alt="Typeface">
                            <h4>Kilde: Designmagic.com 10 bud om typografi</h4>
                            <h3>Nogle typografiske begreber:</h3>
                            <p class="ital">Minuskler</p>
                            <p>De ‘små’ bogstaver</p>
                            <p class="ital">Majuskler</p>
                            <p>De ‘STORE’ bogstaver. Benævnes også ‘versaler’ eller ‘blokbogstaver’</p>
                            <p class="ital">X-height </p>
                            <p>Er højden på minuskel ‘x’, målt fra bundlinien til toppen af bogstavet. Kan bl.a. benyttes til at parre typefaces.</p>
                            <p class="ital">Leading</p>
                            <p>Bedre kendt som ‘linieafstand’. Måles fra bundlinie til bundlinie. Typisk udregnes leading med 120- 130% af skriftstørrelsen.</p>
                            <p class="ital">Kerning</p>
                            <p>Også kendt som ‘knibning’. Afstanden mellem hvert enkelt bogstav kan justeres, således der skabes balance.</p>
                            <p class="ital">Tracking </p>
                            <p>Justerer den overordnede afstand mellem alle bogstaver i et ord, eller en længere markering af ord.</p>
                            <h4>Kilde: farver og typografi 25/9  v Carsten K Bogner</h4>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subges" id="gestalt">
                    <figure class="subkort">
                        <img class="subgespic" src="img/gestalt.png" alt="Gestaltlovene">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Gestaltlove</h2>
							<p>Gestaltlovene handler om perception. Lovene beskriver, hvordan vi sanser, og forsøger at give bud på, hvordan den menneskelige hjerne opfatter sammenhænge i omverdenen.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
							<p>Gestaltlovene øger brugervenligheden og hjælper din bruger med at fokusere på din hjemmesides indhold.</p>
                            <h4>Kilde: https://www.nielsgamborg.dk/?p=gestaltlovene</h4>
                            <p class="ital">Proximity</p>
                            <p>Refererer til, hvor tæt elementer er til hinanden. De stærkeste nærhedsforhold er de mellem overlappende emner, men bare at gruppere objekter i et enkelt område kan også have en stærk nærhedseffekt.</p>
                            <p>Det modsatte kan også være sandt. Ved at placere mellemrum mellem elementer kan du tilføje adskillelse, selvom deres andre egenskaber er de samme.</p>
                            <img src="img/prox.jpg" alt="Proximity">
                            <p>Det modsatte kan også være sandt. Ved at placere mellemrum mellem elementer kan du tilføje adskillelse, selvom deres andre egenskaber er de samme.</p>
							<p class="ital">Continuity</p>
                            <p>Postulerer, at det menneskelige øje vil følge den nemmeste vej, når du ser streger uanset hvordan linjerne faktisk blev trukket.</p>
                            <p>Dette kan være et værdifuldt redskab, når målet er at lede en besøgendes øje i en bestemt retning. De vil følge den enkleste vej på siden, så sørg for, at de mest vitale dele, de skal se, falder inden for den vej. Da øjet følger en linje, vil det naturligt trække øjet fra et emne til det næste.</p>
                            <img src="img/continuity.png" alt="Continuity">
							<p class="ital">Similarity</p>
                            <p>Det er menneskets natur at gruppere tingene sammen. Elementer der ligner hinanden grupperes visuelt, uanset deres nærhed til hinanden. De kan grupperes efter farve, form eller størrelse.</p>
                            <p>Similarity kan bruges til at knytte elementer sammen, som måske ikke er lige ved siden af hinanden i et design.</p>
                            <img src="img/similarity.png" alt="Similarity">
							<p class="ital">Figure-ground</p>
                            <p>Princippet figure-ground ligner closure princippet, det drager fordel af den måde, hjernen bearbejder negative rum. Du har sikkert set eksempler på dette princip, der flyder rundt i memes på sociale medier eller som en del af logoer.</p>
                            <p>Din hjerne vil skelne mellem de objekter, den anser for at være i forgrunden af et billede og baggrunden. Hvor ting bliver interessante er, når forgrunden og baggrunden faktisk indeholder to forskellige billeder, som denne:</p>
                            <img src="img/figure.jpg" alt="Figure-groud">
							<p class="ital">Common fate</p>
                            <p>Dette princip siger, at folk vil gruppere ting, der peger på eller bevæger sig i samme retning.</p>
                            <p>I naturen ser vi dette i ting som fugleflokke eller fiskestimer. De består af en masse individuelle individer, men fordi de tilsyneladende bevæger sig som en, samler vores hjerner dem sammen og betragter dem som en samlet enhed.</p>
                            <img src="img/common.jpg" alt="Common fate">
							<p class="ital">Symmetry</p>
                            <p>Loven om symmetri, hvad dette princip siger er, at din hjerne vil opleve tvetydige figurer på så enkel måde som muligt. For eksempel ses et monokrom version af det olympiske logo som en serie af overlappende cirkler frem for en samling af buede linjer.</p>
                            <img src="img/symmetry.png" alt="Symmetry">
							<p class="ital">Closure</p>
                            <p>Det er tanken om, at din hjerne vil udfylde de manglende dele af et design eller et billede for at skabe en helhed.</p>
                            <p>I sin enkleste form tillader closure princippet, at dit øje følger noget som en linje til dens ende. Men mere komplekse applikationer ses ofte i logoer, som for eksempel World Wildlife Funds logo</p>
                            <p>Store stykker af omridset for pandaen mangler, men din hjerne har ikke noget problem at fylde de manglende sektioner for at se hele dyret.</p>
                            <img src="img/closure.png" alt="Closure">
							<p class="ital">Simplicity</p>
                            <p>Angiver at vores sind opfatter alt i sin enkleste form. Billedet nedenfor, for eksempel når det studeres dybt, består af individuelle komponenter, der ikke har nogen betydning, når de ses separat, men vores sind opfatter dem automatisk i kombination til ordet 'logo'.</p>
                            <img src="img/simplicity.jpg" alt="Simplicity">
							<p class="ital">White space</p>
                            <p>White space er alt det der ikke er der, sagt på en anden måde den baggrund der ikke er udfyldt af andet.</p>
                            <p>Det kan bruges til at trække opmærksomhed mod det der ønskes fremhævet som det væsentlige. En meget kendt side der gør brug af white space ses herunder.</p>
                            <img src="img/white.jpg" alt="White space">
							<p class="ital">Golden section</p>
                            <p>På dansk den gyldne spiral, den har altid eksisteret i naturen, og allerede i oldtidens Grækenland kendte man til og benyttede det bl.a. indenfor arkitekturen.</p>
                            <p>Det kan med fordel benyttes ved opbygning af hjemmesider, da det vil være med til at sikre et harmonisk og behageligt udtryk.</p>
                            <img src="img/golden.png" alt="Golden section">
							<p class="ital">Rule of thirds</p>
                            <p>Er en " tommelfingerregel " eller retningslinje, som gælder for processen med at komponere visuelle billeder såsom design, film, malerier og fotografier.</p>
                            <p>Retningslinjerne foreslår, at et billede opdeles i ni lige store dele af to lige adskilte vandrette linjer og to lodrette linjer med ens adskillelse, og at vigtige sammensætningselementer skal placeres langs disse linjer eller deres kryds. Ved anvendelse af princippet skabes mere spænding, energi og interesse i sammensætningen end blot at centrere emnet.</p>
                            <img src="img/rule.jpg" alt="Rule of thirds">
							<p class="ital">Grids</p>
                            <p>Grids bruges til opbygning af et usynligt gitter der kan dele en side op i et antal felter, både horisontalt og vertikalt. Anvendt på rette måde, kan det være med til at gøre siden mere harmonisk og overskuelig at se på.</p>
                            <img src="img/grids.jpg" alt="Grids">
                            <h4>Kilder: https://www.canva.com/learn/gestalt-theory/ - https://www.toptal.com/designers/ui/gestalt-principles-of-design</h4>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Gestaltlove</h2>
							<p>Gestaltlovene handler om perception. Lovene beskriver, hvordan vi sanser, og forsøger at give bud på, hvordan den menneskelige hjerne opfatter sammenhænge i omverdenen.</p>
							<p>Gestaltlovene øger brugervenligheden og hjælper din bruger med at fokusere på din hjemmesides indhold.</p>
                            <h4>Kilde: https://www.nielsgamborg.dk/?p=gestaltlovene</h4>
                            <p class="ital">Proximity</p>
                            <p>Refererer til, hvor tæt elementer er til hinanden. De stærkeste nærhedsforhold er de mellem overlappende emner, men bare at gruppere objekter i et enkelt område kan også have en stærk nærhedseffekt.</p>
                            <p>Det modsatte kan også være sandt. Ved at placere mellemrum mellem elementer kan du tilføje adskillelse, selvom deres andre egenskaber er de samme.</p>
                            <img src="img/prox.jpg" alt="Proximity">
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
							<p class="ital">Continuity</p>
                            <p>Postulerer, at det menneskelige øje vil følge den nemmeste vej, når du ser streger uanset hvordan linjerne faktisk blev trukket.</p>
                            <p>Dette kan være et værdifuldt redskab, når målet er at lede en besøgendes øje i en bestemt retning. De vil følge den enkleste vej på siden, så sørg for, at de mest vitale dele, de skal se, falder inden for den vej. Da øjet følger en linje, vil det naturligt trække øjet fra et emne til det næste.</p>
                            <img src="img/continuity.png" alt="Continuity">
							<p class="ital">Similarity</p>
                            <p>Det er menneskets natur at gruppere tingene sammen. Elementer der ligner hinanden grupperes visuelt, uanset deres nærhed til hinanden. De kan grupperes efter farve, form eller størrelse.</p>
                            <p>Similarity kan bruges til at knytte elementer sammen, som måske ikke er lige ved siden af hinanden i et design.</p>
                            <img src="img/similarity.png" alt="Similarity">
							<p class="ital">Figure-ground</p>
                            <p>Princippet figure-ground ligner closure princippet, det drager fordel af den måde, hjernen bearbejder negative rum. Du har sikkert set eksempler på dette princip, der flyder rundt i memes på sociale medier eller som en del af logoer.</p>
                            <p>Din hjerne vil skelne mellem de objekter, den anser for at være i forgrunden af et billede og baggrunden. Hvor ting bliver interessante er, når forgrunden og baggrunden faktisk indeholder to forskellige billeder, som denne:</p>
                            <img src="img/figure.jpg" alt="Figure-groud">
							<p class="ital">Common fate</p>
                            <p>Dette princip siger, at folk vil gruppere ting, der peger på eller bevæger sig i samme retning.</p>
                            <p>I naturen ser vi dette i ting som fugleflokke eller fiskestimer. De består af en masse individuelle individer, men fordi de tilsyneladende bevæger sig som en, samler vores hjerner dem sammen og betragter dem som en samlet enhed.</p>
                            <img src="img/common.jpg" alt="Common fate">
							<p class="ital">Symmetry</p>
                            <p>Loven om symmetri, hvad dette princip siger er, at din hjerne vil opleve tvetydige figurer på så enkel måde som muligt. For eksempel ses et monokrom version af det olympiske logo som en serie af overlappende cirkler frem for en samling af buede linjer.</p>
                            <img src="img/symmetry.png" alt="Symmetry">
							<p class="ital">Closure</p>
                            <p>Det er tanken om, at din hjerne vil udfylde de manglende dele af et design eller et billede for at skabe en helhed.</p>
                            <p>I sin enkleste form tillader closure princippet, at dit øje følger noget som en linje til dens ende. Men mere komplekse applikationer ses ofte i logoer, som for eksempel World Wildlife Funds logo</p>
                            <p>Store stykker af omridset for pandaen mangler, men din hjerne har ikke noget problem at fylde de manglende sektioner for at se hele dyret.</p>
                            <img src="img/closure.png" alt="Closure">
							<p class="ital">Simplicity</p>
                            <p>Angiver at vores sind opfatter alt i sin enkleste form. Billedet nedenfor, for eksempel når det studeres dybt, består af individuelle komponenter, der ikke har nogen betydning, når de ses separat, men vores sind opfatter dem automatisk i kombination til ordet 'logo'.</p>
                            <img src="img/simplicity.jpg" alt="Simplicity">
							<p class="ital">White space</p>
                            <p>White space er alt det der ikke er der, sagt på en anden måde den baggrund der ikke er udfyldt af andet.</p>
                            <p>Det kan bruges til at trække opmærksomhed mod det der ønskes fremhævet som det væsentlige. En meget kendt side der gør brug af white space ses herunder.</p>
                            <img src="img/white.jpg" alt="White space">
							<p class="ital">Golden section</p>
                            <p>På dansk den gyldne spiral, den har altid eksisteret i naturen, og allerede i oldtidens Grækenland kendte man til og benyttede det bl.a. indenfor arkitekturen. </p>
                            <p>Det kan med fordel benyttes ved opbygning af hjemmesider, da det vil være med til at sikre et harmonisk og behageligt udtryk. </p>
                            <img src="img/golden.png" alt="Golden section">
							<p class="ital">Golden section</p>
                            <p>På dansk den gyldne spiral, den har altid eksisteret i naturen, og allerede i oldtidens Grækenland kendte man til og benyttede det bl.a. indenfor arkitekturen.</p>
                            <p>Det kan med fordel benyttes ved opbygning af hjemmesider, da det vil være med til at sikre et harmonisk og behageligt udtryk. </p>
                            <img src="img/golden.jpg" alt="Golden section">
							<p class="ital">Rule of thirds</p>
                            <p>Er en " tommelfingerregel " eller retningslinje, som gælder for processen med at komponere visuelle billeder såsom design, film, malerier og fotografier.</p>
                            <p>Retningslinjerne foreslår, at et billede opdeles i ni lige store dele af to lige adskilte vandrette linjer og to lodrette linjer med ens adskillelse, og at vigtige sammensætningselementer skal placeres langs disse linjer eller deres kryds. Ved anvendelse af princippet skabes mere spænding, energi og interesse i sammensætningen end blot at centrere emnet.</p>
                            <img src="img/rule.jpg" alt="Rule of thirds">
							<p class="ital">Grids</p>
                            <p>Grids bruges til opbygning af et usynligt gitter der kan dele en side op i et antal felter, både horisontalt og vertikalt. Anvendt på rette måde, kan det være med til at gøre siden mere harmonisk og overskuelig at se på.</p>
                            <img src="img/grids.jpg" alt="Grids">
                            <h4>Kilder: https://www.canva.com/learn/gestalt-theory/ - https://www.toptal.com/designers/ui/gestalt-principles-of-design</h4>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subfoto" id="foto">
                    <figure class="subkort">
                        <img class="subfotopic" src="img/objektiv.jpg" alt="Fotografering.">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Fotografering</h2>
							<p>Vi har fået en gennemgang af spejlrefleks kameraets opbygning og er blevet introduceret til de grundlæggende funktioner der skal tages i betragtning såfremt man selv vil være herre over sine fotooptagelser.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
							<p>Tidligere var det i højere grad nødvendigt at tage stilling på forhånd til under hvilke omstændigheder der skulle fotograferes end det er i dag. De digitale kameraer gør, at du altid har den rigtige ”film” med i kameraet, der skal altså ikke på forhånd tages højde for om der er behov for en høj eller lav lysfølsomhed (ISO).</p>
                            <p>Stort set alle kameraer er udstyret med en auto funktion der styrer alle indstillinger, det er altså ikke nødvendigt for brugeren at tage stilling til andet end trykke på udløserknappen.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Det er selvfølgelig den mest simple måde at fotografere på, og selvom resultatet i mange tilfælde bliver udmærket, bør autofunktionen ikke anvendes, idet det alene er kameraet der styrer alle indstillinger.</p>
                            <p>Det er derfor no go at bruge denne funktion hvis du selv ønsker at have styr på din optagelse.</p>
                            <p>Det samme gælder de mange programmer der er optimeret til en bestemt type billede, her har man som fotograf heller ikke kontrol over sine optagelser. Derfor, vil du have styr på dine billeder, så anvender du de muligheder der er for manuelt at indstille kameraet.</p>
                            <p>Der findes et kæmpe udvalg af objektiver (linser) til digitale spejlrefleks kameraer, alle har deres helt specielle styrker og svagheder. Det mest almindelige er dog nok for de fleste at det objektiv der er til rådighed, er det standard objektiv der fulgte med kameraet.</p>
                            <img src="img/objektiver.png" alt="Objektiver">
                            <p>Der findes objektiver med fast brændvidde, det mest almindelige er dog nok objektiver hvor der er mulighed for at indstille både brændvidde og blænde. Brændvidden er den afstand der er mellem objektiv og sensor, man kan som tommelfingerregel sig at jo mindre brændvidden er, jo større udsnit af et motiv får man med. Forskellen mellem den mindste og den største brændvidde på et objektiv, kendes mest som objektivets zoom. Brændvidden angives i mm, et objektiv med angivelsen 18-55 har altså en afstand til sensoren på mellem 18 og 55 mm.</p>
                            <p>Blænden styrer hvor meget lys der lukkes ind, blændetal angives med f/ foran tallet, jo mindre blændetallet er jo mere lys lukkes der ind, dybdeskarphed i et billede er en af de ting din blænde har indflydelse på.</p>
                            <p>ISO er censorens følsomhed over for lysmængden, jo mindre lysmængede jo højere ISO er der behov for, det har dog nogen omkostninger at anvende en høj ISO, jo højere denne er jo mere støj kommer der på billedet, så som udgangspunkt skal der anvendes så lav ISO som muligt. Derfor bør der i stedet anvendes længer lukketid hvis det er muligt.</p>
                            <p>Lukketid, er den tid sensoren udsættes for lysindfald, jo længere tid desto mere lys lukkes ind. Ønsker man et billede af et motiv i bevægelse, er det derfor nødvendigt med en kort lukketid for at fastfryse motivet, idet billedet ellers vil blive sløret. Et stillestående motiv kan i modsat fald gives mere liv med en lang lukketid, lange lukketider kræver dog oftest at kameraet placeres på stativ for at undgå rystelser.</p>
                            <p>Lys er en vigtig detalje, for lidt og for meget er lige galt, ekstern lyssætning kan være den eneste måde at få et godt billede, en indbygget blitz er ikke godt for noget, den giver i langt de flest tilfælde et alt for direkte og skarpt lys, røde øjne og kraftige skygger ender ofte med at blive resultatet. En ekstern blitz (speed light) eller fotolamper, hvor der er mulighed for at tilpasse lysmængden eller lave mere diffust lys vil give et langt bedre resultat.</p>
                            <img src="img/lys.jpg" alt="Kamera lamper">
                            <p>Der er ofte mulighed for at indstille hvilket format billederne skal gemme i, vil du være sikker på at få den højeste kvalitet, så vælg RAW, det fylder mere men giver flere muligheder for efterfølgende redigering.</p>
                            <p>Man kan ikke sige at der opnås et godt billede blot ved at indstille en enkelt af ovenstående, det er en kombination af indstillingerne der giver det gode billede.</p>
                            <p>Hvilket mærke der er det bedste, er vist lidt ligesom religion, det den ene tilbeder, kunne en anden aldrig komme i tanke om at købe.</p>
                            <p>Dog siger mange der hævder at være eksperter, at der findes to rigtig gode mærker, Canon og Nikon, og så er der alle de andre.</p>
                            <img src="img/nikon-canon.jpg" alt="Nikon og Canon kamera">
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Fotografering</h2>
							<p>Vi har fået en gennemgang af spejlrefleks kameraets opbygning og er blevet introduceret til de grundlæggende funktioner der skal tages i betragtning såfremt man selv vil være herre over sine fotooptagelser.</p>
                            <p>Tidligere var det i højere grad nødvendigt at tage stilling på forhånd til under hvilke omstændigheder der skulle fotograferes end det er i dag. De digitale kameraer gør, at du altid har den rigtige ”film” med i kameraet, der skal altså ikke på forhånd tages højde for om der er behov for en høj eller lav lysfølsomhed (ISO).</p>
                            <p>Stort set alle kameraer er udstyret med en auto funktion der styrer alle indstillinger, det er altså ikke nødvendigt for brugeren at tage stilling til andet end trykke på udløserknappen.</p>
                            <p>Det er selvfølgelig den mest simple måde at fotografere på, og selvom resultatet i mange tilfælde bliver udmærket, bør autofunktionen ikke anvendes, idet det alene er kameraet der styrer alle indstillinger.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
							<p>
                            <p>Det er derfor no go at bruge denne funktion hvis du selv ønsker at have styr på din optagelse.</p>
                            <p>Det samme gælder de mange programmer der er optimeret til en bestemt type billede, her har man som fotograf heller ikke kontrol over sine optagelser. Derfor, vil du have styr på dine billeder, så anvender du de muligheder der er for manuelt at indstille kameraet.</p>
                            <p>Der findes et kæmpe udvalg af objektiver (linser) til digitale spejlrefleks kameraer, alle har deres helt specielle styrker og svagheder. Det mest almindelige er dog nok for de fleste at det objektiv der er til rådighed, er det standard objektiv der fulgte med kameraet.</p>
                            <img src="img/objektiver.png" alt="Objektiver">
                            <p>Der findes objektiver med fast brændvidde, det mest almindelige er dog nok objektiver hvor der er mulighed for at indstille både brændvidde og blænde. Brændvidden er den afstand der er mellem objektiv og sensor, man kan som tommelfingerregel sig at jo mindre brændvidden er, jo større udsnit af et motiv får man med. Forskellen mellem den mindste og den største brændvidde på et objektiv, kendes mest som objektivets zoom. Brændvidden angives i mm, et objektiv med angivelsen 18-55 har altså en afstand til sensoren på mellem 18 og 55 mm.</p>
                            <p>Blænden styrer hvor meget lys der lukkes ind, blændetal angives med f/ foran tallet, jo mindre blændetallet er jo mere lys lukkes der ind, dybdeskarphed i et billede er en af de ting din blænde har indflydelse på.</p>
                            <p>ISO er censorens følsomhed over for lysmængden, jo mindre lysmængede jo højere ISO er der behov for, det har dog nogen omkostninger at anvende en høj ISO, jo højere denne er jo mere støj kommer der på billedet, så som udgangspunkt skal der anvendes så lav ISO som muligt. Derfor bør der i stedet anvendes længer lukketid hvis det er muligt.</p>
                            <p>Lukketid, er den tid sensoren udsættes for lysindfald, jo længere tid desto mere lys lukkes ind. Ønsker man et billede af et motiv i bevægelse, er det derfor nødvendigt med en kort lukketid for at fastfryse motivet, idet billedet ellers vil blive sløret. Et stillestående motiv kan i modsat fald gives mere liv med en lang lukketid, lange lukketider kræver dog oftest at kameraet placeres på stativ for at undgå rystelser.</p>
                            <p>Lys er en vigtig detalje, for lidt og for meget er lige galt, ekstern lyssætning kan være den eneste måde at få et godt billede, en indbygget blitz er ikke godt for noget, den giver i langt de flest tilfælde et alt for direkte og skarpt lys, røde øjne og kraftige skygger ender ofte med at blive resultatet. En ekstern blitz (speed light) eller fotolamper, hvor der er mulighed for at tilpasse lysmængden eller lave mere diffust lys vil give et langt bedre resultat.</p>
                            <img src="img/lys.jpg" alt="Kamera lamper">
                            <p>Der er ofte mulighed for at indstille hvilket format billederne skal gemme i, vil du være sikker på at få den højeste kvalitet, så vælg RAW, det fylder mere men giver flere muligheder for efterfølgende redigering.</p>
                            <p>Man kan ikke sige at der opnås et godt billede blot ved at indstille en enkelt af ovenstående, det er en kombination af indstillingerne der giver det gode billede.</p>
                            <p>Hvilket mærke der er det bedste, er vist lidt ligesom religion, det den ene tilbeder, kunne en anden aldrig komme i tanke om at købe.</p>
                            <p>Dog siger mange der hævder at være eksperter, at der findes to rigtig gode mærker, Canon og Nikon, og så er der alle de andre.</p>
                            <img src="img/nikon-canon.jpg" alt="Nikon og Canon kamera">
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
        </ul>
    </main>
