    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subpsd">
                <a href="#">
                    <figure class="subkort">
                        <img class="subpsdpic" src="F:\Arbejdsmappe\Eksamen/img/farvel.jpg" alt="Adobe Photoshop">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Photoshop</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p></div>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subill">
                <a href="#">
                    <figure class="subkort">
                        <img class="subillpic" src="F:\Arbejdsmappe\Eksamen/img/kommunikation.jpg" alt="Adobe Illustrator.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Illustrator</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
           </li>
            
            <li class="subkort-emne subft">
                <a href="#">
                    <figure class="subkort">
                        <img class="subftpic" src="F:\Arbejdsmappe\Eksamen/img/web-design.png" alt="Farver og typografi.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Farver og typografi</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subges">
                <a href="#">
                    <figure class="subkort">
                        <img class="subgespic" src="F:\Arbejdsmappe\Eksamen/img/dsthink.png" alt="Gestaltlovene">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Gestaltlove</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subfoto">
                <a href="#">
                    <figure class="subkort">
                        <img class="subfotopic" src="F:\Arbejdsmappe\Eksamen/img/mark.jpg" alt="Fotografering.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Fotografering</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
        </ul>
    </main>
