<header class="masterhead">

<!-- Burgermenu -->
<nav>
    <div class="dropdown">
        <div onclick="myFunction()" class="dropbtn">
                    <span ></span>
                    <span></span>
                    <span></span>
    </div>
    
<!-- Menu indhold -->
    <div id="myDropdown" class="dropdown-content">
        <h1>
            <ul>
                <ul>
                    <li class="menu"><a href="http://gert3987.web.eadania.dk/eksamen/">Home</a>
                    <a href="web.php">Webudvikling</a>
                    <a href="kommunikation.php">Kommunikation</a>
                    <a href="design.php">Design</a>
                    <a href="dthinking.php">Design thinking</a>
                    <a href="onep.php">One page projekt</a>
                    <a href="marketing.php">Online marketing</a>
                    <a href="refl.php">Reflektioner</a></li>
                </ul>
                    <hr>
                <ul>
                    <li class="menu"><a href="#photoshop">Photoshop</a>
                    <a href="#illustrator">Illustrator</a>
                    <a href="#farver">Farver og typografi</a>
                    <a href="#foto">Fotografering</a>
                    <a href="#gestalt">Gestaltlove</a></li>
                </ul>
            </ul>
        </h1>
    </div>
</div>           
</nav>
        
	</header>