    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subdthinking" id="dthinking">
                    <figure class="subkort">
                        <img class="subdthinkingpic" src="img/dthinking.png" alt="Design Thinking">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
							<p>Design Thinking er en metode og mere end det, det er et mind-set, der er med til at styre faserne i et udviklingsprojekt.</p>
							<p>Det handler om at tænke, som navnet antyder. Man kan ikke sige at der er nogen rigtig eller forkert måde at gribe det an på, det det kan være forskelligt fra situation til situation hvordan det er mest hensigtsmæssigt at gribe processen an.</p>
                            <p>Ordet design, dækker ikke kun over at formgive, som multimediedesigner, skal der tænkes mange ting ind i et projekt før det er muligt at fremkomme med et tilfredsstillende design. Farver, typografi og brugervenlighed er blot et par af de ting der gør et design.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Der er mange problemstillinger der skal tages højde for, inden der tages stilling til det endelige design. Her er design thinking en metode til at styre processen, det gælder om at være nysgerrig før man går til løsninger.</p>
                            <p>Design thinking hander også om at inddrage dem der skal bruge din side, ikke kun i starten, men løbende igennem processen. på den måde får du en større forståelse for hvor der skal sættes ind, baseret på mere end blot dine egne antagelser. Herved opnås den største chance for, et det er den optimale løsning der nås. Det skal påpeges at brugerinddragelsen ikke er til for at finde ud af hvad brugerne øsnker, men at få forståelse for deres problemstillinger.</p>
                            <p>Det handler altså om at være nysgerrig og eksperimenterende, hele tiden have focus på brugerne, inddrage dem ved samtale, observationer og lave brugertest når der ligger en prototype klar.</p>
                            <p>Design thinking inddelse i 6 faser, der startes altid i Empathize harefter kan det være nødvendigt at gå tilbage fra de enkelte faser, såfremt det er nødvendigt med nye løsninger og ideer.</p>
                            <h3>Empathize</h3>
                            <p>Det er her man ved nysgerrighed skal klarlægge problemstillingerne i projektet. Brugerindragelse er en vigtig faktor i denne fase, det gøres ved at stille masser hv spørgsmål, observationer og interview med brugere. Det gælder om at være problemet, herved gives den bedste mulighed for at finde den rette løsning.</p>
                            <h3>Define</h3>
                            <p>Det ligger lidt i navnet, at det er her man begynder at definere problemet, med hjælp fra de data og informationer der er indsamlet i empathize fasen. Kategorisering af data, mindmap og spørgsmål til hvordan der kommes frem til en løsning, er nogle af de værktøjer der kan bruges.</p>
                            <h3>Ideate</h3>
                            <p>Nu kan idegenereringen begynde ud fra de ideer og data der er fremkommet i de tidligere faser. Det gælder stadig om at få så mange ting på banen som muligt, for på den måde at finde frem til den bedste løsning på den aktuelle problemstilling.</p>
                            <p>Brainstorm, user path og kategorisering af ideerne er her vigtige redskaber</p>
                            <h3>Prototype</h3>
                            <p>En prototype behøver ikke være digital, det billigste er at udvikle simple prototyper der kan bruges ved brugertest, det kan være simple stregtegninger der skitserer oplægget til det endelige design. Det er ikke så meget indholden på siden der har beytdning, det der skal belyses her er om siden er fornuftig opbygget For at nå frem til en god prototype, skal man i videst muligt omfang forsøge at sætte sig i brugerens sted.</p>
                            <h3>Test</h3>
                            <p>I testfasen er det igen tid til brugerinddragelse, denne gang i en test af prototypen, har vil det vise sig om navigationen er opbygget på en nem og forståelig måde. Kan en bruger der ser dit design for første gang finde rundt på siden, giver det mening for udenforstående, hvis ja, så har du ramt plet, i modsat fald, bruges de indkomne data til at forbedre dit design. Her kan det være nødvendigt at gå tilbage til en af de tidligere faser og samle trådene.</p>
                            <h3>Implementering</h3>
                            <p>Så er tiden inde til at give liv til det endelige oplæg. Prototyper og andet data er på plads så projektet om nødvendigt kan overgives til andre. Det kan være programeringen skal laves eksternt, der kan også være tale om en intern gruppe der ikke har været med i de indledende faser skal være med til at implementere den endelig løsning.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
							<p>Design Thinking er en metode og mere end det, det er et mind-set, der er med til at styre faserne i et udviklingsprojekt.</p>
							<p>Det handler om at tænke, som navnet antyder. Man kan ikke sige at der er nogen rigtig eller forkert måde at gribe det an på, det det kan være forskelligt fra situation til situation hvordan det er mest hensigtsmæssigt at gribe processen an.</p>
                            <p>Ordet design, dækker ikke kun over at formgive, som multimediedesigner, skal der tænkes mange ting ind i et projekt før det er muligt at fremkomme med et tilfredsstillende design. Farver, typografi og brugervenlighed er blot et par af de ting der gør et design.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Der er mange problemstillinger der skal tages højde for, inden der tages stilling til det endelige design. Her er design thinking en metode til at styre processen, det gælder om at være nysgerrig før man går til løsninger.</p>
                            <p>Design thinking hander også om at inddrage dem der skal bruge din side, ikke kun i starten, men løbende igennem processen. på den måde får du en større forståelse for hvor der skal sættes ind, baseret på mere end blot dine egne antagelser. Herved opnås den største chance for, et det er den optimale løsning der nås. Det skal påpeges at brugerinddragelsen ikke er til for at finde ud af hvad brugerne øsnker, men at få forståelse for deres problemstillinger.</p>
                            <p>Det handler altså om at være nysgerrig og eksperimenterende, hele tiden have focus på brugerne, inddrage dem ved samtale, observationer og lave brugertest når der ligger en prototype klar.</p>
                            <p>Design thinking inddelse i 6 faser, der startes altid i Empathize harefter kan det være nødvendigt at gå tilbage fra de enkelte faser, såfremt det er nødvendigt med nye løsninger og ideer.</p>
                            <h3>Empathize</h3>
                            <p>Det er her man ved nysgerrighed skal klarlægge problemstillingerne i projektet. Brugerindragelse er en vigtig faktor i denne fase, det gøres ved at stille masser hv spørgsmål, observationer og interview med brugere. Det gælder om at være problemet, herved gives den bedste mulighed for at finde den rette løsning.</p>
                            <h3>Define</h3>
                            <p>Det ligger lidt i navnet, at det er her man begynder at definere problemet, med hjælp fra de data og informationer der er indsamlet i empathize fasen. Kategorisering af data, mindmap og spørgsmål til hvordan der kommes frem til en løsning, er nogle af de værktøjer der kan bruges.</p>
                            <h3>Ideate</h3>
                            <p>Nu kan idegenereringen begynde ud fra de ideer og data der er fremkommet i de tidligere faser. Det gælder stadig om at få så mange ting på banen som muligt, for på den måde at finde frem til den bedste løsning på den aktuelle problemstilling.</p>
                            <p>Brainstorm, user path og kategorisering af ideerne er her vigtige redskaber</p>
                            <h3>Prototype</h3>
                            <p>En prototype behøver ikke være digital, det billigste er at udvikle simple prototyper der kan bruges ved brugertest, det kan være simple stregtegninger der skitserer oplægget til det endelige design. Det er ikke så meget indholden på siden der har beytdning, det der skal belyses her er om siden er fornuftig opbygget For at nå frem til en god prototype, skal man i videst muligt omfang forsøge at sætte sig i brugerens sted.</p>
                            <h3>Test</h3>
                            <p>I testfasen er det igen tid til brugerinddragelse, denne gang i en test af prototypen, har vil det vise sig om navigationen er opbygget på en nem og forståelig måde. Kan en bruger der ser dit design for første gang finde rundt på siden, giver det mening for udenforstående, hvis ja, så har du ramt plet, i modsat fald, bruges de indkomne data til at forbedre dit design. Her kan det være nødvendigt at gå tilbage til en af de tidligere faser og samle trådene.</p>
                            <h3>Implementering</h3>
                            <p>Så er tiden inde til at give liv til det endelige oplæg. Prototyper og andet data er på plads så projektet om nødvendigt kan overgives til andre. Det kan være programeringen skal laves eksternt, der kan også være tale om en intern gruppe der ikke har været med i de indledende faser skal være med til at implementere den endelig løsning.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subdtprojekt" id="dtprojekt">
                    <figure class="subkort">
                            <img class="subdtprojektpic" src="img/dtkontrakt.jpg" alt="Design Thinking Projekt">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking Projekt</h2>
							<p>Det første længerevarende gruppearbejde bestod af Design Thinking projektet. Opgaven var at udarbejdde et oplæg til en webbaseret app til reservation og udlån. Projektet havde en varighed på en uge.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Rene, Nikolas og jeg var sat i gruppe sammen. Som indledning lavede vi en gruppekontrakt, hvori vi beskrev mødetider, tilgang til gruppearbejdet mv.</p>
                            <p>Vi indledte arbejdet med en brainstorm for at få så mange emner på banene som muligt, herefter skulle vi tage stilling til hvilket emne vi ville arbejde videre med. Vi valgte at det skulle være et system der både kunne bruges til reservation af lokaler og udstyr.</p>
                            <p>Da vi ønskede at få et så godt grundlag som muligt for at tage endelig stilling hvad der skulle med og ikke med, havde vi nogle samtaler med bland andre Mette på kontoret. da disse viste at det ikke var så ligetil med hensyn til reservation af lokaler, valgte vi alene at gå videre med reservation og udlån af udstyr på uddannelsessteder. Vi havde først Dania Skives udlån af fotoudstyr i tankerne, men ønskede at ende op med en løsning som kunne bruges også andre steder til andet udstyr.</p>
                            <img class="scalepic" src="img/dtbstorm1.jpg" alt="Indledende brainstorm">
                            <p>Efter at have valgt hvad vi ville arbejde videre med, havde vi igen en brainstorm, igen for at få så mange ideer som muligt frem i lyset. Herefter kunne vi begynde at kategorisere de forskellige, så vi fik en ide om hvilket omfang der ville ligge i opgaven.</p>
                            <p>Vi ønskede at lave et system der både indeholdt en brugerdel og en administrator del, så det skulle være en fuld funktionsdygtig app, og ikke blot noget der fokuserede alene på brugerdelen.</p>
                            <p>Vi gik nu igang med brugerundersøgelser, hvordan oplevede dem der brugte systemet i dag tingene fungerede, hvor så de problemerne, vi havde en samtale med både Niels og Carsten for at høre hvordan de håndterede det i dag, og hvilke ønsker de kunne have til et mere velfiungerende system.</p>
                            <p>Ud over det, var Nikolas på SOSU skolen i Skive, Rene forsøgte at få nogen i snak på VIA i Skive, og endelig var Nikolas og jeg i Viborg, hvor vi havde samtaler med de ansvarlige på både Dania og VIA. Via har rigtig godt styr på hvem der har lånt hvad, idet det styres gennem deres bibliotekssystem, de kunne dog godt ønske sig en reservationssystem. Hos Dania er det mere det tilfældige søms princip der hersker, enten skrives et udlån i en kalender eller en seddel hænges på opslagstavlen, der er derfor meget begrænset hvor meget styr der er på hvem har lånt hvad og er det afleveret tilbage rettidigt.</p>
                            <a target="blank" href="img/dtbstorm3.jpg"> <img class="scalepic" src="img/dtbstorm3.jpg" alt="Kategorisering af emner"></a>
                            <p>Efter at have indsamlet tilstrækkelig data og bearbejdet det, lavede vi et user path, for at få et overblik over hvordan systemet fungere i dag, og hvad kan gøres for at optimere det.</p>                            
                            <a target="blank" href="img/userpath.jpg"> <img class="scalepic" src="img/userpath.jpg" alt="User path"></a>
                            <p>Tiden var nu inde til at få samlet trådene til en struktur som ville kunne bruges, vi gjorde igen brug af brainstorms, og lavede en grovskitse af hvordan vi gerne ville opbygge vores app.</p>                            
                            <a target="blank" href="img/ideate.jpg"> <img class="scalepic" src="img/ideate.jpg" alt="Skitse over app"></a>
                            <p>Vi benyttede os flittgigt af tavlen under prototyping fasen, her tegnede vi de enkelte skærmbilleder op, på den måde kunne vi se om det fungerede som tænkt.</p>                            
                            <a target="blank" href="img/prototyping.jpg"> <img class="scalepic" src="img/prototyping.jpg" alt="Prototyper tegnes på tavle"></a>
                            <p>Da vi havde et tilfredsstillende, blev der lavet tegninger til udprintning. Disse blev efterfølgende brugt i brugertest som gav anledning til nogle rettelser. Endnu en gang brugertest blev kørt igennem, og herefter kunne vi lave de sidste ændringer og gøre vores prototype klar til implemetering.</p>
                            <p>Implementeringen bestod af at vi skulle overdrage projektet til datamatikerne, dette skulle være i form af en video der forklarede hvordan app'en var tænkt at fungere, herefter kunne der stilles opklarende spørgsmål. Datamatikerne skulle bruge det til en projektopgave, desværre har vi ikke hørt hvordan det siden er gået.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Design Thinking Projekt</h2>
							<p>Det første længerevarende gruppearbejde bestod af Design Thinking projektet. Opgaven var at udarbejdde et oplæg til en webbaseret app til reservation og udlån. Projektet havde en varighed på en uge.</p>
                            <p>Rene, Nikolas og jeg var sat i gruppe sammen. Som indledning lavede vi en gruppekontrakt, hvori vi beskrev mødetider, tilgang til gruppearbejdet mv.</p>
                            <p>Vi indledte arbejdet med en brainstorm for at få så mange emner på banene som muligt, herefter skulle vi tage stilling til hvilket emne vi ville arbejde videre med. Vi valgte at det skulle være et system der både kunne bruges til reservation af lokaler og udstyr.</p>
                            <p>Da vi ønskede at få et så godt grundlag som muligt for at tage endelig stilling hvad der skulle med og ikke med, havde vi nogle samtaler med bland andre Mette på kontoret. da disse viste at det ikke var så ligetil med hensyn til reservation af lokaler, valgte vi alene at gå videre med reservation og udlån af udstyr på uddannelsessteder. Vi havde først Dania Skives udlån af fotoudstyr i tankerne, men ønskede at ende op med en løsning som kunne bruges også andre steder til andet udstyr.</p>
                            <img class="scalepic" src="img/dtbstorm1.jpg" alt="Indledende brainstorm">
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                        <div class="clearfix">
                            <a target="blank" href="img/dtbstorm3.jpg"> <img class="scalepic2" src="img/dtbstorm3.jpg" alt="Kategorisering af emner"></a>
                            <p>Efter at have valgt hvad der skulle arbejdes videre med, havde vi igen en brainstorm, igen for at få så mange ideer som muligt frem i lyset. Herefter kunne vi begynde at kategorisere de forskellige, så vi fik en ide om hvilket omfang der ville ligge i opgaven.</p>
                            <p>Vi ønskede at lave et system der både indeholdt en brugerdel og en administrator del, så det skulle være en fuld funktionsdygtig app, og ikke blot noget der fokuserede alene på brugerdelen.</p>
                            <p>Vi gik nu igang med brugerundersøgelser, hvordan oplevede dem der brugte systemet i dag tingene fungerede, hvor så de problemerne, vi havde en samtale med både Niels og Carsten for at høre hvordan de håndterede det i dag, og hvilke ønsker de kunne have til et mere velfiungerende system.</p>
                            <p>Ud over det, var Nikolas på SOSU skolen i Skive, Rene forsøgte at få nogen i snak på VIA i Skive, og endelig var Nikolas og jeg i Viborg, hvor vi havde samtaler med de ansvarlige på både Dania og VIA. Via har rigtig godt styr på hvem der har lånt hvad, idet det styres gennem deres bibliotekssystem, de kunne dog godt ønske sig en reservationssystem. Hos Dania er det mere det tilfældige søms princip der hersker, enten skrives et udlån i en kalender eller en seddel hænges på opslagstavlen, der er derfor meget begrænset hvor meget styr der er på hvem har lånt hvad og er det afleveret tilbage rettidigt.</p>
                        </div>
                        <div class="clearfix">                             
                            <a target="blank" href="img/userpath.jpg"> <img class="scalepic2" src="img/userpath.jpg" alt="User path"></a>
                            <p>Efter at have indsamlet tilstrækkelig data og bearbejdet det, lavede vi et user path, for at få et overblik over hvordan systemet fungere i dag, og hvad kan gøres for at optimere det.</p>
                        </div>
                        <div class="clearfix">                            
                            <a target="blank" href="img/ideate.jpg"> <img class="scalepic2" src="img/ideate.jpg" alt="Skitse over app"></a>
                            <p>Tiden var nu inde til at få samlet trådene til en struktur som ville kunne bruges, vi gjorde igen brug af brainstorms, og lavede en grovskitse af hvordan vi gerne ville opbygge vores app.</p>
                        </div>
                        <div class="clearfix">                            
                            <a target="blank" href="img/prototyping.jpg"> <img class="scalepic2" src="img/prototyping.jpg" alt="Prototyper tegnes på tavle"></a>
                            <p>Vi benyttede os flittgigt af tavlen under prototyping fasen, her tegnede vi de enkelte skærmbilleder op, på den måde kunne vi se om det fungerede som tænkt.</p>
                            <p>Da vi havde et tilfredsstillende, blev der lavet tegninger til udprintning. Disse blev efterfølgende brugt i brugertest som gav anledning til nogle rettelser. Endnu en gang brugertest blev kørt igennem, og herefter kunne vi lave de sidste ændringer og gøre vores prototype klar til implemetering.</p>
                            <p>Implementeringen bestod af at vi skulle overdrage projektet til datamatikerne, dette skulle være i form af en video der forklarede hvordan app'en var tænkt at fungere, herefter kunne der stilles opklarende spørgsmål. Datamatikerne skulle bruge det til en projektopgave, desværre har vi ikke hørt hvordan det siden er gået.</p>
                        </div>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
        </ul>
    </main>
