    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subdthinking" id="dthinking">
                    <figure class="subkort">
                        <img class="subdthinkingpic" src="img/dthinking.png" alt="Design Thinking">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
							<p>Design Thinking er en metode og mere end det, det er et mind-set, der er med til at styre faserne i et udviklingsprojekt.</p>
							<p>Det handler om at tænke, som navnet antyder. Man kan ikke sige at der er nogen rigtig eller forkert måde at gribe det an på, det det kan være forskelligt fra situation til situation hvordan det er mest hensigtsmæssigt at gribe processen an.</p>
                            <p>Ordet design, dækker ikke kun over at formgive, som multimediedesigner, skal der tænkes mange ting ind i et projekt før det er muligt at fremkomme med et tilfredsstillende design. Farver, typografi og brugervenlighed er blot et par af de ting der gør et design.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Der er mange problemstillinger der skal tages højde for, inden der tages stilling til det endelige design. Her er design thinking en metode til at styre processen, det gælder om at være nysgerrig før man går til løsninger.</p>
                            <p>Design thinking hander også om at inddrage dem der skal bruge din side, ikke kun i starten, men løbende igennem processen. på den måde får du en større forståelse for hvor der skal sættes ind, baseret på mere end blot dine egne antagelser. Herved opnås den største chance for, et det er den optimale løsning der nås. Det skal påpeges at brugerinddragelsen ikke er til for at finde ud af hvad brugerne øsnker, men at få forståelse for deres problemstillinger.</p>
                            <p>Det handler altså om at være nysgerrig og eksperimenterende, hele tiden have focus på brugerne, inddrage dem ved samtale, observationer og lave brugertest når der ligger en prototype klar.</p>
                            <p>Design thinking inddelse i 6 faser, der startes altid i Empathize harefter kan det være nødvendigt at gå tilbage fra de enkelte faser, såfremt det er nødvendigt med nye løsninger og ideer.</p>
                            <h3>Empathize</h3>
                            <p>Det er her man ved nysgerrighed skal klarlægge problemstillingerne i projektet. Brugerindragelse er en vigtig faktor i denne fase, det gøres ved at stille masser hv spørgsmål, observationer og interview med brugere. Det gælder om at være problemet, herved gives den bedste mulighed for at finde den rette løsning.</p>
                            <h3>Define</h3>
                            <p>Det ligger lidt i navnet, at det er her man begynder at definere problemet, med hjælp fra de data og informationer der er indsamlet i empathize fasen. Kategorisering af data, mindmap og spørgsmål til hvordan der kommes frem til en løsning, er nogle af de værktøjer der kan bruges.</p>
                            <h3>Ideate</h3>
                            <p>Nu kan idegenereringen begynde ud fra de ideer og data der er fremkommet i de tidligere faser. Det gælder stadig om at få så mange ting på banen som muligt, for på den måde at finde frem til den bedste løsning på den aktuelle problemstilling.</p>
                            <p>Brainstorm, user path og kategorisering af ideerne er her vigtige redskaber</p>
                            <h3>Prototype</h3>
                            <p>En prototype behøver ikke være digital, det billigste er at udvikle simple prototyper der kan bruges ved brugertest, det kan være simple stregtegninger der skitserer oplægget til det endelige design. Det er ikke så meget indholden på siden der har beytdning, det der skal belyses her er om siden er fornuftig opbygget For at nå frem til en god prototype, skal man i videst muligt omfang forsøge at sætte sig i brugerens sted.</p>
                            <h3>Test</h3>
                            <p>I testfasen er det igen tid til brugerinddragelse, denne gang i en test af prototypen, har vil det vise sig om navigationen er opbygget på en nem og forståelig måde. Kan en bruger der ser dit design for første gang finde rundt på siden, giver det mening for udenforstående, hvis ja, så har du ramt plet, i modsat fald, bruges de indkomne data til at forbedre dit design. Her kan det være nødvendigt at gå tilbage til en af de tidligere faser og samle trådene.</p>
                            <h3>Implementering</h3>
                            <p>Så er tiden inde til at give liv til det endelige oplæg. Prototyper og andet data er på plads så projektet om nødvendigt kan overgives til andre. Det kan være programeringen skal laves eksternt, der kan også være tale om en intern gruppe der ikke har været med i de indledende faser skal være med til at implementere den endelig løsning.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
							<p>Design Thinking er en metode og mere end det, det er et mind-set, der er med til at styre faserne i et udviklingsprojekt.</p>
							<p>Det handler om at tænke, som navnet antyder. Man kan ikke sige at der er nogen rigtig eller forkert måde at gribe det an på, det det kan være forskelligt fra situation til situation hvordan det er mest hensigtsmæssigt at gribe processen an.</p>
                            <p>Ordet design, dækker ikke kun over at formgive, som multimediedesigner, skal der tænkes mange ting ind i et projekt før det er muligt at fremkomme med et tilfredsstillende design. Farver, typografi og brugervenlighed er blot et par af de ting der gør et design.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Der er mange problemstillinger der skal tages højde for, inden der tages stilling til det endelige design. Her er design thinking en metode til at styre processen, det gælder om at være nysgerrig før man går til løsninger.</p>
                            <p>Design thinking hander også om at inddrage dem der skal bruge din side, ikke kun i starten, men løbende igennem processen. på den måde får du en større forståelse for hvor der skal sættes ind, baseret på mere end blot dine egne antagelser. Herved opnås den største chance for, et det er den optimale løsning der nås. Det skal påpeges at brugerinddragelsen ikke er til for at finde ud af hvad brugerne øsnker, men at få forståelse for deres problemstillinger.</p>
                            <p>Det handler altså om at være nysgerrig og eksperimenterende, hele tiden have focus på brugerne, inddrage dem ved samtale, observationer og lave brugertest når der ligger en prototype klar.</p>
                            <p>Design thinking inddelse i 6 faser, der startes altid i Empathize harefter kan det være nødvendigt at gå tilbage fra de enkelte faser, såfremt det er nødvendigt med nye løsninger og ideer.</p>
                            <h3>Empathize</h3>
                            <p>Det er her man ved nysgerrighed skal klarlægge problemstillingerne i projektet. Brugerindragelse er en vigtig faktor i denne fase, det gøres ved at stille masser hv spørgsmål, observationer og interview med brugere. Det gælder om at være problemet, herved gives den bedste mulighed for at finde den rette løsning.</p>
                            <h3>Define</h3>
                            <p>Det ligger lidt i navnet, at det er her man begynder at definere problemet, med hjælp fra de data og informationer der er indsamlet i empathize fasen. Kategorisering af data, mindmap og spørgsmål til hvordan der kommes frem til en løsning, er nogle af de værktøjer der kan bruges.</p>
                            <h3>Ideate</h3>
                            <p>Nu kan idegenereringen begynde ud fra de ideer og data der er fremkommet i de tidligere faser. Det gælder stadig om at få så mange ting på banen som muligt, for på den måde at finde frem til den bedste løsning på den aktuelle problemstilling.</p>
                            <p>Brainstorm, user path og kategorisering af ideerne er her vigtige redskaber</p>
                            <h3>Prototype</h3>
                            <p>En prototype behøver ikke være digital, det billigste er at udvikle simple prototyper der kan bruges ved brugertest, det kan være simple stregtegninger der skitserer oplægget til det endelige design. Det er ikke så meget indholden på siden der har beytdning, det der skal belyses her er om siden er fornuftig opbygget For at nå frem til en god prototype, skal man i videst muligt omfang forsøge at sætte sig i brugerens sted.</p>
                            <h3>Test</h3>
                            <p>I testfasen er det igen tid til brugerinddragelse, denne gang i en test af prototypen, har vil det vise sig om navigationen er opbygget på en nem og forståelig måde. Kan en bruger der ser dit design for første gang finde rundt på siden, giver det mening for udenforstående, hvis ja, så har du ramt plet, i modsat fald, bruges de indkomne data til at forbedre dit design. Her kan det være nødvendigt at gå tilbage til en af de tidligere faser og samle trådene.</p>
                            <h3>Implementering</h3>
                            <p>Så er tiden inde til at give liv til det endelige oplæg. Prototyper og andet data er på plads så projektet om nødvendigt kan overgives til andre. Det kan være programeringen skal laves eksternt, der kan også være tale om en intern gruppe der ikke har været med i de indledende faser skal være med til at implementere den endelig løsning.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subdtprojekt" id="dtprojekt">
                    <figure class="subkort">
                        <img class="subdtprojektpic" src="img/dtprojekt.jpg" alt="Design Thinking Projekt">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking Projekt</h2>
							<p>Det første længerevarende gruppearbejde bestod af Design Thinking projektet. Opgaven var at udarbejdde et oplæg til en webbaseret app til reservation og udlån.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Design Thinking Projekt</h2>
							<p>Det første længerevarende gruppearbejde bestod af Design Thinking projektet. Opgaven var at udarbejdde et oplæg til en webbaseret app til reservation og udlån.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>                      
                                                
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
                </a>
            </li>
            
        </ul>
    </main>
