    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subdthinking" id="dthinking">
                <a href="#">
                    <figure class="subkort">
                        <img class="subdthinkingpic" src="img/dthinking.png" alt="Design Thinking">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subdtprojekt" id="dtprojekt">
                <a href="#">
                    <figure class="subkort">
                        <img class="subdtprojektpic" src="img/dtprojekt.jpg" alt="Design Thinking Projekt">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking Projekt</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
        </ul>
    </main>
