<!-- Denne side er udarbejdet af Gert Jørgensen som eksamensprojekt i forbindelse med  1. semesters afslutning af uddannelsen til multimediedesigner på Erhvervsakademi Dania i Skive 2018. -->

<main id="content" class="main-area">
    <ul class="index">

<!-- Om mig -->

    <li class="kort-emne me">
        <section class="kort">
            <section class="billedtekst">
                <div class="clearfix">
                    <img class="mepic" src="img/gj600.jpg" alt="Kursist billede.">
                        <h1 class="billedtekst-titel">Læringsportefolio</h1>
                            <p>Jeg hedder Gert, jeg studerer til multimediedesigner på Erhverveakademi Dania i Skive.</p>
                            <p>Denne side udgør eksamensprojekt for 1. semester.</p>
                            <p>Jeg vil på denne side gennemgå de forskellinge fag og projekter der er blevet arbejdet med. Det vil ikke være en fuldstændig fyldestgørende gennemgang af hele semestret, men mere beskrivelse af det der erfter min mening har været det væsentligste.</p>
                    </div>
                </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                    </section>
        </section>
    </li>

<!-- webudvikling -->

    <li class="kort-emne web">        
            <section class="kort">
                <section class="billedtekst">
                    <div class="clearfix">
                    <a href="web.php">
                        <img class="scalepic50l" src="img/web-design.png" alt="Webudvikling.">
                            <h2 class="billedtekst-titel">Webudvikling</h2>
                                <p>HTML. CSS. CSS Grid. Versionsstyring. Servere og klienter. Lidt historie.</p>
                                <p>Hvad er HTML og CSS? Det vil jeg blandt andet forsøge at give et lille indblik i under dette emne.</p>
                                <p>Der vil også være lidt om versionsstyring og hvorfor der er vigtigt, samt en en smule om internettets historie.</p>
                            </a>
                        </div>
                    </section>

                    <section class=tiltop>
                        <a href="#">Til toppen</a>
                    </section>
            </section>
        </li>

<!-- Design -->

    <li class="kort-emne design">
            <section class="kort">
                <section class="billedtekst">
                    <div class="clearfix">
                    <a href="design.php">
                        <h2 class="billedtekst-titel">Design</h2>
                            <img class="scalepic50r" src="img/farvel.jpg" alt="Design.">
                                <p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                                <p>Her vil jeg fortælle om hvad vi har beskæftiget os med indenfor design.</p>
                                <p>Hvad er Photshop og Illustrator?.</p>
                                <p>Hvad er forskellen på RBG og CMYK farver?.</p>
                                <p>Typografi, det er da bare de fonts jeg bruger, eller hvad?.</p>
                                <p>Fotografering, hvorfor det er vigtigt selv at have kontrollen med kameraet. Vi krattet lidt i overfladen i forhold til hvad der har betydning.</p>
                            </a>
                        </div>
                    </section>

                    <section class=tiltop>
                        <a href="#">Til toppen</a>
                    </section>
            </section>
        </li>

<!-- Kommunikation -->

    <li class="kort-emne komm">
            <section class="kort">
                <section class="billedtekst">
                    <div class="clearfix">
                    <a href="kommunikation.php">
                        <img class="scalepic30l" src="img/kommunikation.jpg" alt="Kommunikation.">
                            <h2 class="billedtekst-titel">Kommunikation</h2>
                                <p>Kommunikation og produktionsmodeller. Præsentationsteknik. Tekstproduktion. Business Model Canvas</p>
                                <p>En lille gennemgang af de værktøjer der kan være en hjælp til en bedre kommunikation.</p>
                            </a>
                        </div>
                    </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                </section>
            </section>
        </li>

<!-- Design thinking -->

    <li class="kort-emne think">
            <section class="kort">
                <section class="billedtekst">
                    <div class="clearfix">
                    <a href="dthinking.php">
                        <img class="scalepic30r" src="img/dsthink.png" alt="Ideer bag værktøjet Design Thinking.">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
                                <p>Kort fortalt om Design Thinking. Design thinking projekt.</p>
                                <p>Arbejdet i forbindelse med vores Design Thinking projekt og hvad det endte ud i.</p>
                            </a>
                        </div>
                    </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                </section>
            </section>
        </li>

<!-- Alt det andet -->

    <li class="kort-emne andet">
            <section class="kort">
                <section class="billedtekst">
                    <div class="clearfix">
                    <a href="andet.php">
                        <img class="scalepic30l" src="img/andet.jpg" alt="Alt det andet.">
                            <h2 class="billedtekst-titel">Alt det andet</h2>
                                <p>Her kan læses lidt om Online Marketing.</p>
                                <p>Virksomhedsbesøg</p>
                                <p>Quick and Dirty video og Dialog med håndgribelige genstande.</p>
                            </a>
                        </div>
                    </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                </section>
            </section>
        </li>

<!-- One page projekt -->

    <li class="kort-emne onepage">
            <section class="kort">
                <section class="billedtekst">
                    <div class="clearfix">
                    <a href="onep.php">
                        <img class="scalepic30r" src="img/bent.png" alt="Onepage.">
                            <h2 class="billedtekst-titel">One Page Projekt</h2>
                                <p>Vores One page projekt.</p>
                                <p>Den første rigtige store udfordring i forbindelse med programmering og styling.</p>
                                <p>Sejre, nederlag, frustrationer, glæde og så selvfølgelig Biotex Bent.</p>
                            </a>
                        </div>                        
                </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                    </section>
            </section>
        </li>

<!-- Refleksioner -->

    <li class="kort-emne refl">
            <section class="kort">
                <section class="billedtekst">
                    <div class="clearfix">
                    <a href="refl.php">
                        <img class="scalepic30l" class="reflpic" src="img/reflek.jpg" alt="Reflektioner.">
                            <h2 class="billedtekst-titel">Refleksioner</h2>
                                <p>Tanker omkring uddannelse og undervisning.</p>
                                <p>Her vil jeg forsøge at beskrive lidt af processen omkring projekt portefolio.</p>
                                <p>Giver det mening?.</p>
                            </a>
                        </div>
                    </section>

                    <section class=tiltop>
                        <a href="#">Til toppen</a>
                    </section>
            </section>
        </li>
    </ul>
</main>
