    <main id="content" class="main-area">
        <ul class="index">
            <li class="kort-emne me">
                <a href="#">
                    <figure class="kort">
                        <img class="mepic" src="img/gj900.jpg" alt="Kursist billede.">
                            <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Læringsportefolio</h2>
							<p>Jeg hedder Gert, jeg studerer til multimediedesigner på Erhverveakademi Dania i Skive.</p>
                            
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            <li class="kort-emne web">
                <a href="design.php">
                    <figure class="kort">
                        <img class="webpic" src="img/web-design.png" alt="Webudvikling.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Webudvikling</h2>
							<p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            <li class="kort-emne design">
                <a href="design.php">
                    <figure class="kort">
                        <img class="designpic" src="img/farvel.jpg" alt="Design.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design</h2>
							<p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            <li class="kort-emne komm">
                <a href="design.php">
                    <figure class="kort">
                        <img class="kommpic" src="img/kommunikation.jpg" alt="Kommunikation.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Kommunikation</h2>
							<p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            <li class="kort-emne think">
                <a href="dthinking.php">
                    <figure class="kort">
                        <img class="thinkpic" src="img/dsthink.png" alt="Ideer bag værktøjet Design Thinking.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
							<p>Design thinking som værktøj. Design thinking projekt.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            <li class="kort-emne mark">
                <a href="design.php">
                    <figure class="kort">
                        <img class="markpic" src="img/mark.jpg" alt="Marketing.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Online Marketing</h2>
							<p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            <li class="kort-emne onepage">
                <a href="design.php">
                    <figure class="kort">
                        <img class="onepagepic" src="img/bent.png" alt="Onepage.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">One Page Projekt</h2>
							<p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            <li class="kort-emne refl">
                <a href="design.php">
                    <figure class="kort">
                        <img class="reflpic" src="img/reflek.jpg" alt="Reflektioner.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Reflektioner</h2>
							<p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denne side udgør eksamensprojekt for 1. semester, og består af en læringsportefølje.
                            </p>
                            <p>Jeg vil efter bedste evne gennemgå de forskellige fag og projekter der er blevet arbejdet med. Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
        </ul>
    </main>
