    <main id="content" class="main-area">
        <ul class="index">
            <li class="kort-emne me">
                <figure class="kort">
                    <img class="mepic" src="img/gj600.jpg" alt="Kursist billede.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Læringsportefolio</h2>
							<p>Jeg hedder Gert, jeg studerer til multimediedesigner på Erhverveakademi Dania i Skive.</p> 
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Denne side udgør eksamensprojekt for 1. semester.
                            </p>
                            <p>Jeg vil på denne side gennemgå de forskellinge fag og projekter der er blevet arbejdet med. Det vil ikke være en fuldstændig fyldestgørende gennemgang af hele semestret, men mere beskrivelse af det jeg har fundet mest væsentligt.Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                            <p>Jeg vil også komme med lidt personlige reflektioner i forhold til uddannelsen.
                            </p>
                        </figcaption>
                </figure>
            </li>
            
            <li class="kort-emne web">
                <a href="web.php">
                    <figure class="kort">
                        <img class="webpic" src="img/web-design.png" alt="Webudvikling.">
                       <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Webudvikling</h2>
							<p>HTML. CSS. CSS Grid. Versionsstyring. Servere og klienter. Lidt historie.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Hvad er HTML og CSS? Det vil jeg blandt andet forsøge at give et lille indblik i under dette emne.
                            </p>
                            <p>Der vil også være lidt om versionsstyring og hvorfor der er vigtigt, samt en en smule om internettets historie.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="kort-emne design">
                <a href="design.php">
                    <figure class="kort">
                        <img class="designpic" src="img/farvel.jpg" alt="Design.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design</h2>
							<p>Photoshop. Illustrator. Farver og typografi. Gestaltlove. Fotografering.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Her vil jeg fortælle om hvad vi har beskæftiget os med indenfor design.
                            </p>
                            <p>Hvad er Photshop og Illustrator?.
                            </p>
                            <p>Hvad er forskellen på RBG og CMYK farver?.
                            </p>
                            <p>Typografi, det er da bare de fonts jeg bruger, eller hvad?.
                            </p>
                            <p>Fotografering, hvorfor det er vigtigt selv at have kontrollen med kameraet.
                            Vi krattet lidt i overfladen i forhold til hvad der har betydning.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="kort-emne komm">
                <a href="kommunikation.php">
                    <figure class="kort">
                        <img class="kommpic" src="img/kommunikation.jpg" alt="Kommunikation.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Kommunikation</h2>
							<p>Kommunikation og produktionsmodeller. Præsentationsteknik. Tekstproduktion. Business Model Canvas</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>En lille gennemgang af de værktøjer der kan være en hjælp til en bedre kommunikation.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="kort-emne think">
                <a href="dthinking.php">
                    <figure class="kort">
                        <img class="thinkpic" src="img/dsthink.png" alt="Ideer bag værktøjet Design Thinking.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Design Thinking</h2>
							<p>Design thinking som værktøj. Design thinking projekt.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Kort fortalt om Design Thinking.
                            </p>
                            <p>Arbejdet i forbindelse med vores Design Thinking projekt og hvad det endte ud i.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="kort-emne mark">
                <a href="marketing.php">
                    <figure class="kort">
                        <img class="markpic" src="img/mark.jpg" alt="Marketing.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Online Marketing</h2>
							<p>SEO. Sociale medier. Google Add Words.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Online marketing er mere end blot betalte annoncer.
                            </p>
                            <p>Vil man betale for al sin annoncering eller er tanken mere at få den gratis reklame med.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="kort-emne onepage">
                <a href="onep.php">
                    <figure class="kort">
                        <img class="onepagepic" src="img/bent.png" alt="Onepage.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">One Page Projekt</h2>
							<p>Vores One page projekt. Biotex Bent.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Denn første rigtige store udfordring i forbindelse med programmering og styling.
                            </p>
                            <p>Sejre, nederlag, frustrationer, glæde og så selvfølgelig Biotex Bent.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="kort-emne refl">
                <a href="refl.php">
                    <figure class="kort">
                        <img class="reflpic" src="img/reflek.jpg" alt="Reflektioner.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Reflektioner</h2>
							<p>Tanker omkring uddannelse og undervisning.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Her vil jeg forsøge at beskrive mine tanker og ideer..
                            </p>
                            <p>Giver det mening?.
                            </p>
                        </figcaption>
                    </figure>
                </a>
            </li>
        </ul>
    </main>
