    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subkommunikation" id="kommunikation">>
                    <figure class="subkort">
                        <img class="subkommunikationpic" src="img/komm.jpg" alt="Kommunikation og produktions modeller">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Kommunikation og produktions modeller</h2>
							<p>Kommunikation er mere end blot ord, det vi siger og gør, det vi ikke siger og ikke gør.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Stort set alt vi foretager os er kommunikation, det være sig kropssprog, brugen af billeder, designet af en hjemmeside, alt dette er kommunikation som der bør overvejes så den rette målgruppe rammes.</p>
                            <p>Der findes grundlæggende tre former for kommunikation.</p>
                            <p>Verbal (Det talte sprog)</p>
                            <p>Non verbal (Gestetik og Mimik)</p>
                            <p>Skriftlig (Det der kan læses)</p>
                            <p>Hvem vi siger det til, og måden det bliver sagt er heller ikke uden betydning.</p>
                            <p>Konkurent kommunikation, er når der er sammenhæng mellem det man siger og det man gør.</p>
                            <p>Inkonkurent kommunikation, her er der ikke sammenhæng mellem det man siger og det man gør.</p>
                            <h3>Synkron og asynkron kommunikation, handler om kommunikation i forhold til tid:</h3>
                            <p>Synkron kommunikation vil sige at de kommunikerende skriver eller taler sammen på samme tid.</p>
                            <p>Asynkron kommunikation betyder at deltagerne skriftligt kan kommunikere sammen, men at der som oftest er en tidsforskydning i kommunikationen.</p>
                            <h3>5 grundantagelser om kommunikation:</h3>
                            <p>Det er ikke muligt at undlade at kommunikere.</p>
                            <p>Kommunikation består af to dele: Indhold og indbyrdes forhold mellem de deltagende parter i kommunikationen.</p>
                            <p>Udtryk og måden vi tolker kommunikationen på, afhænger af det forhold man har til den der kommunikeres med.</p>
                            <p>Der kommunikeres med både digital kode og analog kode.</p>
                            <p>Digital kode, hvad der siges.</p>
                            <p>Analog kode, hvordan det siges / tonefald, kropssprog, skrifttype og opsætning.</p>
                            <p>Symetrisk og asymetrisk kommunikationsudveksling er afhængig af om den hviler på lighed eller forskel på magt.</p>
                            <h3>Kommunikationsparadigmer:</h3>
                            <p>Paradigmer er en måde at se verden på.</p>
                            <p>Vi har primært arbejdet med to paradigmer, det samfundsvidenskabelige paradigme og det humanistiske paradigme.</p>
                            <h3>Det samfundsvidenskabelig paradigme.</h3>
                            <p>Metoder til analyse af det samfundsvidenskabelige paradigme.</p>
                            <p class="ital">Laswells formel</p>
                            <img src="img/laswells.png" alt="Laswells metode">
                            <p>og AIDA</p>
                            <p>AIDA modellen bruges til at forudsige effekten af en besked. (kvantitav data)</p>
                            <p>Benyttes eksempelvis, ved bruger undersøgelser der skal analyseres i forhold til de indkomne data. Således det bliver mere klart, hvordan kommunikationen målrettes i forhold til hvilken awareness der skal lægges mest vægt på</p>
                            <img src="img/aida.png" alt="AIDA modellen">
                            <p>Benyttes eksempelvis, ved bruger undersøgelser der skal analyseres i forhold til de indkomne data. Således det bliver mere klart, hvordan kommunikationen målrettes i forhold til hvilken awareness der skal lægges mest vægt på</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Kommunikation og produktions modeller</h2>
							<p>Kommunikation er mere end blot ord, det vi siger og gør, det vi ikke siger og ikke gør. Stort set alt vi foretager os er kommunikation, det være sig kropssprog, brugen af billeder, designet af en hjemmeside, alt dette er kommunikation som der bør overvejes så den rette målgruppe rammes.</p>
                            <p>Der findes grundlæggende tre former for kommunikation.</p>
                            <p>Verbal (Det talte sprog)</p>
                            <p>Non verbal (Gestetik og Mimik)</p>
                            <p>Skriftlig (Det der kan læses)</p>
                            <p>Hvem vi siger det til, og måden det bliver sagt er heller ikke uden betydning.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Konkurent kommunikation, er når der er sammenhæng mellem det man siger og det man gør.</p>
                            <p>Inkonkurent kommunikation, her er der ikke sammenhæng mellem det man siger og det man gør.</p>
                            <h3>Synkron og asynkron kommunikation, handler om kommunikation i forhold til tid:</h3>
                            <p>Synkron kommunikation vil sige at de kommunikerende skriver eller taler sammen på samme tid.</p>
                            <p>Asynkron kommunikation betyder at deltagerne skriftligt kan kommunikere sammen, men at der som oftest er en tidsforskydning i kommunikationen.</p>
                            <h3>5 grundantagelser om kommunikation:</h3>
                            <p>Det er ikke muligt at undlade at kommunikere.</p>
                            <p>Kommunikation består af to dele: Indhold og indbyrdes forhold mellem de deltagende parter i kommunikationen.</p>
                            <p>Udtryk og måden vi tolker kommunikationen på, afhænger af det forhold man har til den der kommunikeres med.</p>
                            <p>Der kommunikeres med både digital kode og analog kode.</p>
                            <p>Digital kode, hvad der siges.</p>
                            <p>Analog kode, hvordan det siges / tonefald, kropssprog, skrifttype og opsætning.</p>
                            <p>Symetrisk og asymetrisk kommunikationsudveksling er afhængig af om den hviler på lighed eller forskel på magt.</p>
                            <h3>Kommunikationsparadigmer:</h3>
                            <p>Paradigmer er en måde at se verden på.</p>
                            <p>Vi har primært arbejdet med to paradigmer, det samfundsvidenskabelige paradigme og det humanistiske paradigme.</p>
                            <h3>Det samfundsvidenskabelig paradigme.</h3>
                            <p>Metoder til analyse af det samfundsvidenskabelige paradigme.</p>
                            <h3 class="ital">Laswells formel:</h3>
                            <img src="img/laswells.png" alt="Laswells metode">
                            <p>og AIDA</p>
                            <p>AIDA modellen bruges til at forudsige effekten af en besked. (kvantitav data)</p>
                            <p>Benyttes eksempelvis, ved bruger undersøgelser der skal analyseres i forhold til de indkomne data. Således det bliver mere klart, hvordan kommunikationen målrettes i forhold til hvilken awareness der skal lægges mest vægt på</p> 
                            <img src="img/aida.png" alt="AIDA modellen">
                            <p></p>
                            <div class="dokumentlink">
                            <a target="blank" href="pdf/analyse_budweiser.pdf">Vi benyttede i et gruppearbejde begge modeller til at analysere en Budwieser reklame. Læs den her.</a>
                            </div>
                        </figcaption>
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subpræsentation" id="præs">
                    <figure class="subkort">
                        <img class="subpræsentationpic" src="img/praesentation.jpg" alt="Præsentationsteknik.">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Præsentationsteknik</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Præsentationsteknik</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
           </li>
            
            <li class="subkort-emne subtekst" id="tekstp">
                    <figure class="subkort">
                        <img class="subtekstpic" src="img/tekst.jpg" alt="Tekstproduktion.">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Tekstproduktion</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Tekstproduktion</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
            
            <li class="subkort-emne subbusiness" id="business">
                    <figure class="subkort">
                        <img class="subbusinesspic" src="img/bmc.jpg" alt="Business Model Canvas">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Business Model Canvas</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                            <h2 class="billedtekst-titel">Business Model Canvas</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
        </ul>
    </main>
