<!-- Denne side er udarbejdet af Gert Jørgensen som eksamensprojekt i forbindelse med  1. semesters afslutning af uddannelsen til multimediedesigner på Erhvervsakademi Dania i Skive 2018. -->

<!-- Kommunikation og produktions modeller -->

<main id="content" class="main-area">
    <ul class="subindex">
        <li class="subkort-emne subkommunikation" id="kommunikation">
            <section class="subkort">
                <section class="billedtekst">
                    <div class="clearfix">
                        <img class="scalepic50l" src="img/komm.jpg" alt="Kommunikation og produktions modeller">
                        <h2 class="billedtekst-titel">Kommunikation og produktions modeller</h2>    
                        <p>Kommunikation er mere end blot ord, det vi siger og gør, det vi ikke siger og ikke gør.</p>
                        <p>Stort set alt vi foretager os er kommunikation, det være sig kropssprog, brugen af billeder, designet af en hjemmeside, alt dette er kommunikation som der bør overvejes så den rette målgruppe rammes.</p>
                        
                    </div>
                        
                        <p>Der findes grundlæggende tre former for kommunikation.</p>
                        <p>Verbal (Det talte sprog)</p>
                        <p>Non verbal (Gestetik og Mimik)</p>
                        <p>Skriftlig (Det der kan læses)</p>
                        <p>Hvem vi siger det til, og måden det bliver sagt er heller ikke uden betydning.</p>
                        <p>Konkurent kommunikation, er når der er sammenhæng mellem det man siger og det man gør.</p>
                        <p>Inkonkurent kommunikation, her er der ikke sammenhæng mellem det man siger og det man gør.</p>
                        <h3>Synkron og asynkron kommunikation, handler om kommunikation i forhold til tid:</h3>
                        <p>Synkron kommunikation vil sige at de kommunikerende skriver eller taler sammen på samme tid.</p>
                        <p>Asynkron kommunikation betyder at deltagerne skriftligt kan kommunikere sammen, men at der som oftest er en tidsforskydning i kommunikationen.</p>
                        <h3>5 grundantagelser om kommunikation:</h3>
                    <p>Det er ikke muligt at undlade at kommunikere.</p>
                    <p>Kommunikation består af to dele: Indhold og indbyrdes forhold mellem de deltagende parter i kommunikationen.</p>
                    <p>Udtryk og måden vi tolker kommunikationen på, afhænger af det forhold man har til den der kommunikeres med.</p>
                    <p>Der kommunikeres med både digital kode og analog kode.</p>
                    <p>Digital kode, hvad der siges.</p>
                    <p>Analog kode, hvordan det siges / tonefald, kropssprog, skrifttype og opsætning.</p>
                    <p>Symemtrisk og asymmetrisk kommunikationsudveksling er afhængig af om den hviler på lighed eller forskel på magt.</p>
                    <h3>Kommunikationsparadigmer:</h3>
                    <p>Paradigmer er en måde at se verden på.</p>
                    <p>Vi har primært arbejdet med to paradigmer, det samfundsvidenskabelige paradigme og det humanistiske paradigme.</p>
                    <h3>Det samfundsvidenskabelige paradigme.</h3>
                    <p>Metoder til analyse af det samfundsvidenskabelige paradigme.</p>
                    <p class="ital">Laswells formel</p>
                    <img src="img/laswells.png" alt="Laswells metode">
                    
                    <p>og AIDA</p>
                    <p>AIDA modellen bruges til at forudsige effekten af en besked. (kvantitav data)</p>
                    <p>Benyttes eksempelvis, ved bruger undersøgelser der skal analyseres i forhold til de indkomne data. Således det bliver mere klart, hvordan kommunikationen målrettes i forhold til hvilken awareness der skal lægges mest vægt på</p>
                    <a href="img/aida.png" target="_blank">
                    <img class="scalepic50m" src="img/aida.png" alt="AIDA modellen"></a>
                    <div class="dokumentlink">
                        <a target="blank" href="pdf/analyse_budweiser.pdf">Vi benyttede i et gruppearbejde begge modeller til at analysere en Budwieser reklame. Læs den her.</a>
                    </div>
                    <h3>Det humanistiske paradigme.</h3>
                    <p>Også kaldet interaktionsparadigmet, da der foregår en kommunikation mellem afsender og modtager. Undersøgelser lægger vægt på de kvalitative værdier. Her lægges vægt på individet, der bygges på få men nøje udvalgte modtagere.</p>
                    <p>Ved analyse af det humanistiske paradigme anvendes <h3>IMK modellen.</h3> (InterkulturelMarkedsKommunikation)
                    <img class="scalepic50m" src="img/imk.png" alt="IMK modellen">
                    <p>I forbindelse med websites bør der bruges en kommunikationsform der engagere så målgruppen er medskaber, dette giver en symmetrisk tovejs kommunikation hvor målgruppen deltager og giver feedback.</p>
                    <h4>Kilde: Uddrag af Mariann Platen Daugaards præsentation d.11.09.2018</h4>
                </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                </section>
            </section>
        </li>

        <!-- Præsentationsteknik -->

        <li class="subkort-emne subpræsentation" id="præs">
            <section class="subkort">
                <section class="billedtekst">
                    <div class="clearfix">
                        <img class="scalepic50r" src="img/praesentation.jpg" alt="Præsentationsteknik.">
                        <h2 class="billedtekst-titel">Præsentationsteknik</h2>
                        <h3>Hovedformålet med en præsentation:</h3>
                        <p>Informere.</p>
                        <p>Overtale. (sælge)</p>
                        <p>Underholde.</p>
                        <p>Skabe og fastholde interesse.</p>
                        <p>Det er vigtigt at kende kommunikationssituationen.</p>
                        <p>Kend dine modtagere, dit budskab, og dig selv som afsender. Hvem siger hvad til hvem. Ha kontrol over dit stof, ha kontrol over dig selv og dit kropssprog.</p>
                        <p>Minimer nervøsitet vha. visualisering, planlægning ned i mindste detalje, have målet for øje og sæt din frygt i perspektiv.</p>
                        
                        </div>
                        <p>Hvad er det værste der kan ske?</p>
                        <p>Og tag så en dyb indånding.</p>
                        <a href="img/peterp.png" target="_blank">
                        <img class="scalepic50m" src="img/peterp.png" alt="Peter Plys"></a>
                        <p>Det er vigtigt at gøre sig klart at taler skal varieres, der er naturligvis forskel på om talen er en juridisk tale i en retssal, om det er en politisk tale ved Folketingets åbning, om det talen onkel/morfars 75 års fødselsdag (eller ditto bryllupsdag), eller om der tales til åbningen af en bro, lukningen af en arbejdsplads eller om det er nytåret, der skydes ind.</p>
                        <p>Ved en tales opbygning kan man anvende fiskemodellen, herved sikrer man sig at det er til at finde hoved og hale i det der skal siges.</p>
                        <a href="img/fisk.png" target="_blank">
                        <img class="scalepic50m" src="img/fisk.png" alt="Fiskemodellen"></a>
                        <p>Humor er altid godt til at fange publikum med, nok ikke lige til en begravelse men i de fleste tilfælde kan det give en god start. Og så er det vigtigt at tænke over at ens kropssprog svarer overens med det der siges, i modsat fald kan det let komme til at virke utroværdigt og overfladisk.</p>
                        <h4>Kilde: Uddrag af Mariann Platen Daugaards præsentation d.18.09.2018</h4>
                    
                </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                </section>
            </section>
        </li>

<!-- Tekstproduktion -->

        <li class="subkort-emne subtekst" id="tekstp">
            <section class="subkort">
                <section class="billedtekst">
                    <div class="clearfix">
                        <img class="scalepic50r" src="img/tekst.jpg" alt="Tekstproduktion.">
                        <h2 class="billedtekst-titel">Tekstproduktion</h2>
                        <p>Ved udarbejdelse af tekster, bør de 5 nyhedskriterier altid tages i betragtning: Væsentlighed, sensation, konflikt, identifikation, aktualitet.</p>
                        <p>Ved at anvende nyhedskriterierne opnås en højere kvalitet, der er større chance for at ramme den målgruppe teksten er skrevet til.</p>
                        <p>Dette vil kunne højne interessen så læseren fastholdes i længere tid, ved web tekster har det betydning for hvor mange delinger der vil komme på bland andet de sociale medier. Det kan være afgørende for om din tekst er i stand til at trække besøgende til en webside eller ej.</p>
                        <p>Den gode tekst er også med til at give en bedre SEO, som i sidste ende har stor betydning for, at opnå en bedre placering ved søgning via søgemaskiner.</p>
                        <p>En meget vigtig ting at tage i betragtning, er hvor og til hvem teksten skrives. Det er jo ikke ligegyldigt, om du skriver et brev til tante Oda eller en nyhedsartikel.</p>
                        <p>Hvor der ved, nyhedsartikler, brochure, annoncer og webtekster er mere klare regler der skal tages i anvendelse, er det på sociale medier ikke muligt på samme måde, at opsætte faste regler og modeller, da der her er en langt større grad af spontanitet.</p>
                        <p>Nyhedstrekanten er en skrivemodel der også kan bruges ved udarbejdelse af webtekster, her startes med at konkludere, hvad teksten handler om, det du vil fortælle. Derefter skrives de vigtigste oplysninger, der har fører dig frem til konklusionen.</p>
                        <a href="img/nyhedstrekanten.jpg" target="_blank">
                        <img class="scalepic50m" src="img/nyhedstrekanten.jpg" alt="Nyhedstrekanten"></a>
                        <p>Vi har som opgave skullet udarbejde tre tekster til en virksomhed, en nyhedsartikel, en annonce og et opslag til sociale medier (Facebook).</p>
                        <div class="dokumentlink">
                            <a target="blank" href="pdf/webtekster.pdf">Se mine tekster her.</a>
                        </div>
                        <h3><p class="ital">Jeg gør opmærksom på at der er tale om ren fiktion, der er altså ikke tale om nyheder udgivet på opfordring af virksomheden.</p></h3>
                    </div>
                </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                </section>
            </section>
        </li>

<!-- Business Model Canvas -->

        <li class="subkort-emne subbusiness" id="business">
            <section class="subkort">
                <section class="billedtekst">
                    <div class="clearfix">
                        <img class="scalepic50r" src="img/bmc.jpg" alt="Business Model Canvas">
                        <h2 class="billedtekst-titel">Business Model Canvas</h2>
                        <p>Business Model Canvas er en analysemetode, der kan være med til at give en forståelse for en virksomhed på flere forskellige niveauer.</p>
                        <p>Det første der skal klarlægges er hvilken type virksomhed der er tale om.</p>
                        <p>Herefter kommer en række spørgsmål omkring virksomhedens vision og mission. hvad er formålet med virksomheden, hvad ønsker virksomheden at gøre for hvem, hvem er virksomhedens målgruppe, i hvilket segment befinder virksomheden sig, osv.</p>
                        <p>Det gælder altså om at stille så mange spørgsmål som muligt, jo flere spørgsmål jo mere præcist billede vil man få af, hvad det er for en virksomhed man har med at gøre.</p>
                        <p>Vi har i forbindelse med et gruppearbejde benyttet Business Model Canvas metoden til en analyse af Ryan Air.</p>
                        <p>Det startede ud med, at vi i hver gruppe at sætte ting på hver vores Business Model Canvas, herefter skulle vi samle det til et fælles. der var flere sammenfaldende emner, men alligevel også en del forskelligheder, dette viser tydeligt at det kan være fornuftigt at involvere flere personer når en virksomhed skal analyseres.</p>
                        <a href="img/bmc2.jpg" target="_blank">
                        <img class="scalepic50m" src="img/bmc2.jpg" alt="Business Model Canvas gruppearbejde"></a>
                        <p>Her er det samlet med gule og grønne sedler, som viser at de forskellige grupper havde forskellige ting med.</p>
                        <p>Mange virksomheder har stort fokus på Value Proposition. Det er her, man definerer og tydeliggør, hvilken værdi virksomhedens produkter og services giver dens kunder. Men selv en fantastisk Value Proposition, er ikke garanti for succes. Succes kræver nemlig, at din virksomhed samtidig har en forretningsmodel, der sikrer, at virksomheden har en struktur, der betyder, at du også kan tjene penge.</p>
                    </div>
                </section>

                <section class=tiltop>
                    <a href="#">Til toppen</a>
                </section>
            </section>
        </li>

<!-- Brugertest og videnskabsteori -->

        <li class="subkort-emne subbruger" id="bruger">
            <section class="subkort">
            <div>
                        <h2 class="billedtekst-titel">Brugertest og videnskabsteori</h2>
                        
                <div class="clearfix">
                        <img class="scalepic50l" src="img/videnskab.jpg" alt="Brugertest">
                    <section class="billedtekst">
                        <p>Hvad ser du? Et elskende par eller en flok delfiner?</p>
                        <p>Videnskabsteori defineres som teorien om videnskab. Videnskabsteori beskæftiger sig med spørgsmål som: Hvad er egentlig videnskab? Hvordan producerer man viden? Forholdet mellem videnskab og virkelighed.</p>
                        <h3>Brugertest:</h3>
                        <p>Forskellige antagelser om sandhed. Er der en sand virkelighed - eller er alle sandheder relative? Altså at al sandhed er ”sandhed”. Videnskabsteori er søgen efter sandheden.</p>
                        <p>Vigtigheden ved at anvende videnskabsteori er at klarlægge ting uden for vores egen antagelser, din oplevelse af virkeligheden er ikke nødvendigvis den samme for alle andre.</p>
                        <p>Når man udfører en eller flere brugertests gøres det ud fra en idé om brugerinddragelse. Brugerinddragelse handler om at forstå brugernes behov, motivation og adfærd.</p>
                        <p>Brugerinddragelse handler om at inddrage brugerne, for at validere den navigation, prioritering, kommunikation eller andet, der udvikles på den pågældende brugergrænseflade f.eks. en hjemmeside.</p>
                        <p>Når man arbejder med brugerinddragelse, fokuserer man på at inddrage brugerne som medudviklere af nye digitale løsninger og processer. Brugerne er således med til at kvalitetssikre løsningen.</p>
                        <p>Man kan blandt andet udføre brugertest på:</p>
                        <p>- en eksisterende hjemmeside</p>
                        <p>– en digital/analog prototype (skitser på papir eller klikbare skitser på computer)</p>
                        <p>– en nyimplementeret hjemmeside</p>
                        <p>Formålet er at undersøge om brugerne kan finde rundt i en ny indholdsstruktur, forstå sproget, forstå navigationen, anvende funktionerne osv.</p>
                        <p>Det er brugernes egne forståelser af fx funktion og navngivning, der fungerer som rettesnor.</p>
                        <h3>Metodiske overvejelser:</h3>
                        <p>Hvad er det, jeg vil undersøge?  Hvilke spørgsmål, skal undersøgelsen besvare? Hvad skal undersøgelsens resultater bruges til?</p>
                        <p>Vigtigt for at sikre en god undersøgelse og dermed indsamle korrekt og brugbar viden.</p>
                        <p>Samlet: Hvordan udvikler jeg et undersøgelsesdesign, der bedst muligt besvarer mine spørgsmål?</p>
                        <img src="img/datakilder.png" alt="Primære og sekundære datakilder">
                        <h3>Research paradigmer:</h3>
                        <p class="ital">Kvalitativ metode:</p>
                        <p>I de kvalitative metoder indsamles data, som ikke kan udtrykkes i eksakte talstørrelser, fx om holdninger og adfærd, altså indsamling af bløde data.</p>
                        <p>Kvalitativ metode handler om at forstå de tanker, følelser og overvejelser, respondenterne gør sig.</p>
                        <p>Indsamlingsmetoder:</p>
                        <p>Interview</p>
                        <p>Fokusgrupper</p>
                        <p>Observationer</p>
                        <p>Man bruger åbne ”hv-spørgsmål”. Hvordan? Hvorfor? Osv.</p>
                        <p>Data vil ofte være i form af lange/korte interviews/samtaler med en eller flere personer</p>
                        <p>Databearbejdningen består af at fortolke og analysere</p>
                        <a href="img/paradigmer.png" target="_blank">
                        <img class="scalepic50m" src="img/paradigmer.png" alt="Primære og sekundære datakilder"></a>
                        <p class="ital">Kvantitativ metode:</p>
                        <p>I de kvalitative metoder indsamles hårde data, dvs. størrelser som det er muligt at sætte tal på (eks. spørgeskema)</p>
                        <p>Handler ikke om at forstå, hvorfor folk mener eller gør, som de gør. Vi er groft sagt ligeglade med at forstå deres overvejelser.</p>
                        <p>Antager, at det der måles kan måles og kvanitificeres.</p>
                        <p>Oftest et større datamateriale end ved kvalitative undersøgelser.</p>
                        <p>Det giver større mulighed for at generalisere resultaterne</p>
                        <p>Det handler om at forklare – ikke forstå.</p>
                        <p>Data vil ofte være i form af observationer eller besvarelser af såkaldte lukkede spørgsmål, hvor respondenterne har kunnet vælge mellem flere prædefinerede svarmuligheder.</p>
                        <h4>Kilde: Mariann Platen Daugaards præsentation d.10.10.2018</h4>
                    </section>
                </div>
</div>
                <section class=tiltop>
<a href="#">Til toppen</a>
</section>
            </section>
        </li>
    </ul>
</main>
