    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subonep" id="onep">
                    <figure class="subkort">
                        <img class="suboneppic" src="img/ski.png" alt="One Page">
                        
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">One Page</h2>
							<p>One page projektet var en opgave hvor vi kun skulle være to i hver gruppe, det var med nogen spænding jeg kiggede efter hvem jeg skulle have dette parløb med. Det glædede mig da jeg så at det var Søren jeg skulle lave dette projekt med.</p>
							<p>Vi fik et utroligt godt samarbejde igennem hele forløbet, hvor vi fik brugt en masse af de ting vi har lært i løbet af 1. semester.</p>
                            <p>I det hele taget kan man sige at det var første gang vi rigtigt kom ned substansen af uddannelsen, det var 2½ uge hvor man bagefter virkelig føler man har fået tilført en masse ny viden.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                        <div class="clearfix">
							<img class="scalepic30r" src="img/biotex.jpg" alt="Biotex Ultimate Color">
                            <p>Niels havde ved projektets start medbragt en stribe produkter som blev fordelt ved lodtrækning, Søren og jeg fik udleveret en dunk Biotex Ultimate Color, der er et superkoncentreret vaskemiddel.</p>
                            <p>Efter at have fået vores produkt, var det bare med at kome igang. vi gik straks igang med empathize fasen, Søren og jeg indledte en sand brainstorm, hvor alt vi vidste og ikke vidste om vaskemidler kom på tavlen</p>
							<a target="blank" href="img/tavle.jpg"> <img class="scalepic30r" src="img/tavle.jpg" alt="Brainstorm kategoriseret"></a>
                            <p>Man kan sige vi vendte hver en sten for at få så mange ting frem som muligt. Ideerne var så mange at vi endte med at sortere dem i kategorier for at skabe overblik.</p>
							<a target="blank" href="img/fakta2.jpg"> <img class="scalepic30r" src="img/fakta2.jpg" alt="Faktas reol med vaskemidler"></a>
                            <p>Den megen hjernegymnastik gjorde at vi dagen efter besluttede at tage en interview tur ud i den virkelige verden. Vi havde undret os over at biotex ikke havde nogen form for miljømærkning, det blandt de ting vi ville forsøge at finde et svar på. Vi lagede ud med et besøg hos Fakta, hvor en meget beredvillig butikschef fortalte hvordan deres reoler blev sat op, og hvad der bestemte placeringen at de enkelte mærker som butikken fører.</p>
                            <p>Også hos Føtex mødte vi stor hjælpsomhed, butikschefen og den ansvarlige for afdelingen med rengøringsmidler blev tilkaldt, her fik vi indsamlet en del informationer til senere brug for vores projekt. De kunne ikke svare på den manglende miljømærkning, men blot sige at de der købte Biotex, ikke sådan lige købte andet, var der udsolgt af et Biotex produkt, blev der ikke taget en erstatningsvare istedet. Det fortalte os at Biotex kunder er meget loyale overfor mærket, ligeledes fik vi at vide det var mest den modne forbruger der brugta Biotex, alt sammen nyttige oplysninger som vi kunne bruge efterfølgende.</p>
							<a target="blank" href="img/føtex.jpg"> <img class="scalepic30m" src="img/føtex.jpg" alt="Føtex reol med vaskemidler"></a>
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                        </div>
                            <p>Der var ikke mange mannesker i butikkerne på tidspunktet for vores eksterne undersøgelser, så vi havde en del interviews med medstuderende omkring deres kendskab til Biotex. Her fandt vi ud af at Biotex er et brand alle kender, men blandt unge mennesker anses det lidt som et produkt mor eller mormor bruger, det var senere med til beslutningen om at vi med vores onepage ville henvende os til det yngre publikum.</p>
				        <a target="blank" href="img/interview.jpg"> <img class="scalepic30m" src="img/interview.jpg" alt="Bruger interview"></a>
                            <p>Da al den indkomne data var analyseret og efter endnu en brainstorm, endte vi med en beslutning om, at siden skulle være mere til information end til salg, og at målgruppen skulle være 18-34 år.</p>
                            
                        <div class="dokumentlink">
                            <a target="blank" href="pdf/userstories.pdf">3 User stories.</a>
                        </div>
                            
                            <p>Her i starten af designfasen, kom der en ekstra "person" med i gruppen, om det var kedsomhed eller en pludselig indskydelse der fik Søren til at tegne en karakter på whiteboard ved jeg ikke, men en lidt nutty udseende type tone frem, han blev hurtigt døbt Biotex Bent og ende med at blive omdrejningpunktet for projektets videre forløb.</p>
                            <p>Det var også Biotex Bent der var medvirkende til at holde humøret højt i de pressede situationer der opsto i de efterfølgende faser af projektet.</p>
                            <p>Vi udarbejdede feature/unfeature liste og indholdshieraki, så vi havde styr på hvad der skulle med på siden og i hvilken rækkefølge</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst3">
                        <div class="clearfix">
                        
				        <img class="scalepic30r" src="img/biotex.jpg" alt="Biotex Ultimate Color">
                            <h2 class="billedtekst-titel">One Page</h2>
							<p>One page projektet var en opgave hvor vi kun skulle være to i hver gruppe, det var med nogen spænding jeg kiggede efter hvem jeg skulle have dette parløb med. Det glædede mig da jeg så at det var Søren jeg skulle lave dette projekt med.</p>
							<p>Vi fik et utroligt godt samarbejde igennem hele forløbet, hvor vi fik brugt en masse af de ting vi har lært i løbet af 1. semester.</p>
                            <p>I det hele taget kan man sige at det var første gang vi rigtigt kom ned substansen af uddannelsen, det var 2½ uge hvor man bagefter virkelig føler man har fået tilført en masse ny viden.</p>
                            <p>Niels havde ved projektets start medbragt en stribe produkter som blev fordelt ved lodtrækning, Søren og jeg fik udleveret en dunk Biotex Ultimate Color, der er et superkoncentreret vaskemiddel.</p>
                        </div>
                        </figcaption>
                        
                        <figcaption class="billedtekst4">
                        <div class="clearfix">
                        
				        <img class="scalepic20r" src="img/tavle.jpg" alt="Brainstorm kategoriseret">
				        <img class="scalepic20l" src="img/fakta2.jpg" alt="Faktas reol med vaskemidler">
                            <p>Efter at have fået vores produkt, var det bare med at kome igang. vi gik straks igang med empathize fasen, Søren og jeg indledte en sand brainstorm, hvor alt vi vidste og ikke vidste om vaskemidler kom på tavlen, man kan sige vi vendte hver en sten for at få så mange ting frem som muligt. Ideerne var så mange at vi endte med at sortere dem i kategorier for at skabe overblik.</p>
                            <p>Den megen hjernegymnastik gjorde at vi dagen efter besluttede at tage en interview tur ud i den virkelige verden. Vi havde undret os over at biotex ikke havde nogen form for miljømærkning, det blandt de ting vi ville forsøge at finde et svar på. Vi lagede ud med et besøg hos Fakta, hvor en meget beredvillig butikschef fortalte hvordan deres reoler blev sat op, og hvad der bestemte placeringen at de enkelte mærker som butikken fører.</p>
				        <img class="scalepic30m" src="img/føtex.jpg" alt="Føtex reol med vaskemidler">
                            <p>Også hos Føtex mødte vi stor hjælpsomhed, butikschefen og den ansvarlige for afdelingen med rengøringsmidler blev tilkaldt, her fik vi indsamlet en del informationer til senere brug for vores projekt. De kunne ikke svare på den manglende miljømærkning, men blot sige at de der købte Biotex, ikke sådan lige købte andet, var der udsolgt af et Biotex produkt, blev der ikke taget en erstatningsvare istedet. Det fortalte os at Biotex kunder er meget loyale overfor mærket, ligeledes fik vi at vide det var mest den modne forbruger der brugta Biotex, alt sammen nyttige oplysninger som vi kunne bruge efterfølgende.</p>
                    <hr class="line">
				        <img class="scalepic20r" src="img/interview.jpg" alt="Bruger interview">
                            <p>Der var ikke mange mennesker i butikkerne på tidspunktet for vores eksterne undersøgelser, så vi havde en del interviews med medstuderende omkring deres kendskab til Biotex. Her fandt vi ud af at Biotex er et brand alle kender, men blandt unge mennesker anses det lidt som et produkt mor eller mormor bruger, det var senere med til beslutningen om at vi med vores onepage ville henvende os til det yngre publikum.</p>
                        </div>
                    <hr class="line">
                        <div class="clearfix">
                            <p>Da al den indkomne data var analyseret, endte vi med en beslutning om, at siden skulle være mere til information end til salg, og at målgruppen skulle være 18-34 år.</p>
                            <p>Vi udarbejdede ud fra det vores user stories.</p>
                            
                        <div class="dokumentlink">
                            <a target="blank" href="pdf/userstories.pdf">3 User stories.</a>
                        </div>
                        
                        <img class="scalepic30r" src="img/biobent.jpg" alt="Biotex Bent er født">
                            <p>Her i starten af designfasen, kom der en ekstra "person" med i gruppen, om det var kedsomhed eller en pludselig indskydelse der fik Søren til at tegne en karakter på whiteboard ved jeg ikke, men en lidt nutty udseende type tone frem, han blev hurtigt døbt Biotex Bent og ende med at blive omdrejningpunktet for projektets videre forløb.</p>
                            <p>Det var også Biotex Bent der var medvirkende til at holde humøret højt i de pressede situationer der opstod i de efterfølgende faser af projektet.</p>
                        </div>
                    <hr class="line">
                        
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </figure>
            </li>
        </ul>
    </main>
