<!-- Denne side er udarbejdet af Gert Jørgensen som eksamensprojekt i forbindelse med  1. semesters afslutning af uddannelsen til multimediedesigner på Erhvervsakademi Dania i Skive 2018. -->

    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subonep" id="onep">
                    <section class="subkort">
                        
                        <section class="billedtekst">
                    <div class="clearfix">
                        
                        <a href="img/biotex.jpg" target="_blank">
				        <img class="scalepic20r" src="img/biotex.jpg" alt="Biotex Ultimate Color"></a>
                            <h2 class="billedtekst-titel">One Page</h2>
							<p>One page projektet var en opgave hvor vi kun skulle være to i hver gruppe, det var med nogen spænding jeg kiggede efter hvem jeg skulle have dette parløb med. Det glædede mig da jeg så at det var Søren jeg skulle lave dette projekt med.</p>
							<p>Vi fik et utroligt godt samarbejde igennem hele forløbet, hvor vi fik brugt en masse af de ting vi har lært i løbet af 1. semester.</p>
                            <p>I det hele taget kan man sige at det var første gang vi rigtigt kom ned substansen af uddannelsen, det var 2½ uge hvor man bagefter virkelig føler man har fået tilført en masse ny viden.</p>
                            <p>Niels havde ved projektets start medbragt en stribe produkter som blev fordelt ved lodtrækning, Søren og jeg fik udleveret en dunk Biotex Ultimate Color, der er et superkoncentreret vaskemiddel.</p>
                        </div>
                           
                    <hr class="line">
                        <div class="clearfix">
                        
                        <a href="img/tavle.jpg" target="_blank">
				        <img class="scalepic20r" src="img/tavle.jpg" alt="Brainstorm kategoriseret"></a>
                        <a href="img/fakta2.jpg" target="_blank">
				        <img class="scalepic20l" src="img/fakta2.jpg" alt="Faktas reol med vaskemidler"></a>
                        
                            <p>Efter at have fået vores produkt, var det bare med at komme igang. vi gik straks i gang med empathize fasen, Søren og jeg indledte en sand brainstorm, hvor alt vi vidste og ikke vidste om vaskemidler kom på tavlen, man kan sige vi vendte hver en sten for at få så mange ting frem som muligt. Ideerne var så mange at vi endte med at sortere dem i kategorier for at skabe overblik.</p>
                            <p>Den megen hjernegymnastik gjorde at vi dagen efter besluttede at tage en interviewtur ud i den virkelige verden. Vi havde undret os over at biotex ikke havde nogen form for miljømærkning, det blandt de ting vi ville forsøge at finde et svar på. Vi lagede ud med et besøg hos Fakta, hvor en meget beredvillig butikschef fortalte hvordan deres reoler blev sat op, og hvad der bestemte placeringen at de enkelte mærker som butikken fører.</p>
                            </div>
                        <div class="clearfix">
                        <a href="img/fotex.jpg" target="_blank">
				        <img class="scalepic30m" src="img/fotex.jpg" alt="Føtex reol med vaskemidler"></a>
                            <p>Også hos Føtex mødte vi stor hjælpsomhed, butikschefen og den ansvarlige for afdelingen med rengøringsmidler blev tilkaldt, her fik vi indsamlet en del informationer til senere brug for vores projekt. De kunne ikke svare på den manglende miljømærkning, men blot sige at de der købte Biotex, ikke sådan lige købte andet, var der udsolgt af et Biotex produkt, blev der ikke taget en erstatningsvare i stedet. Det fortalte os at Biotex kunder er meget loyale overfor mærket, ligeledes fik vi at vide det mest er den modne forbruger der bruger Biotex, alt sammen nyttige oplysninger som vi kunne bruge efterfølgende.</p>
                    <hr class="line">
                    <a href="img/interview.jpg" target="_blank">
				        <img class="scalepic20r" src="img/interview.jpg" alt="Bruger interview"></a>
                            <p>Der var ikke mange mennesker i butikkerne på tidspunktet for vores eksterne undersøgelser, så vi havde en del interviews med medstuderende omkring deres kendskab til Biotex. Her fandt vi ud af at Biotex er et brand alle kender, men blandt unge mennesker anses det lidt som et produkt mor eller mormor bruger, det var senere med til beslutningen om at vi med vores onepage ville henvende os til det yngre publikum.</p>
                        </div>
                    <hr class="line">
                        <div class="clearfix">
                            <p>Da al den indkomne data var analyseret, endte vi med en beslutning om, at siden skulle være mere til information end til salg, og at målgruppen skulle være 18-34 år.</p>
                            <p>Vi udarbejdede ud fra det vores user stories.</p>
                            
                        <div class="dokumentlink">
                            <a target="blank" href="pdf/userstories.pdf">3 User stories.</a>
                        </div>
                        
                        <a href="img/biobent.jpg" target="_blank">
                        <img class="scalepic30r" src="img/biobent.jpg" alt="Biotex Bent er født"></a>
                            <p>Her i starten af designfasen, kom der en ekstra "person" med i gruppen, om det var kedsomhed eller en pludselig indskydelse der fik Søren til at tegne en karakter på whiteboard ved jeg ikke, men en lidt nutty udseende type tone frem, han blev hurtigt døbt Biotex Bent og ende med at blive omdrejningspunktet for projektets videre forløb.</p>
                            <p>Det var også Biotex Bent der var medvirkende til at holde humøret højt i de pressede situationer der opstod i de efterfølgende faser af projektet.</p>
                        </div>
                    <hr class="line">
                        <div class="clearfix">
                        <a href="img/indhold.jpg" target="_blank">
                        <img class="scalepic20r" src="img/indhold.jpg" alt="Indholdshieraki"></a>
                        <a href="img/wireframe.jpg" target="_blank">
                        <img class="scalepic20l" src="img/wireframe.jpg" alt="Wireframes"></a>
                            <p>Vi udarbejdede feature/unfeature liste og indholdshieraki, så vi havde styr på hvad der skulle med på siden og i hvilken rækkefølge</p>
                            <p>Wireframes til tre forskellige skærmtyper blev tegnet på whiteboard, vi brugte farvemarkeringer så det var parret med vores indholds hierarki, det gav et hurtigt overblik om hvor de forskellige emner skulle placeres.</p>
                         </div>   
                    <hr class="line">
                    <div class="clearfix">
                        <a href="img/moodboard.jpg" target="_blank">
                        <img class="scalepic20l" src="img/moodboard.jpg" alt="Moodboard"></a>
                        <a href="img/kaffe.jpg" target="_blank">
                        <img class="scalepic20r" src="img/kaffe.jpg" alt="Kaffepause"></a>
                            <p>Vores moodboard blev vist mere vildledende end vejledende, der gik lidt meget normalmanden, Biotex Bent, hamp, og andet i til det var nemt at forstå hvor vi ville hen med det, men som Bent ville sige, hvad betyder det, bare man har det sjovt, og har Biotex i tankerne.</p>
                            <p>Selv i en presset tid er der plads til en kop kaffe.</p>
                        </div>   
                    <hr class="line">
                    <div class="clearfix">
                    <a href="img/onepagefront.jpg" target="_blank">
                    <img class="scalepic20r" src="img/onepagefront.jpg" alt="Den første færdige forside"></a>
                            <p>Vi startede programmeringen ud efter princippet mobile first, det gik ganske smertefrit i starten, siden begyndte at tage form. Vi havde gemt billeder i 3 formater, tanken var at bruge et format til hver størrelse skærm, her havde vi load tider i tankerne. Det skulle senere vise sig at give nogle problemer.</p>
                            <p>Vores "forside" så efterhånden ud som vi havde tænkt, og vi var klar til at gå videre med indholdet, vi præsenterede det foreløbige resultat for Carsten, han var ikke ubetinget imponeret, og mente at Biotex Bent ville blive alt for overeksponeret, medmindre vi havde tænkt os at fortsætte som en tegneserie. Dette ville dog efter Carstens mening kræve langt flere forskellige tegninger af Bent. Vi kunne godt se pointen i det, og da det ikke lå lige for at skulle tegne bent i mange flere versioner, blev det foreløbige layout til dels skrottet. Der skulle nytænkes, med nye billeder osv.</p>
                            <p>Nu skulle der efterhånden arbejdes hurtigt, der kom rimeligt hurtigt styr på de ændringer vi mente var nødvendige, det øvrige indhold kom stille og roligt på plads.</p>
                            <p>Til sidst var det blot at lave grids til tablet og desktop, det burde jo være ligetil, men ak og ve, det skabte store problemer, nok mest fordi vi ikke helt havde tænkt det helt igennem, og det trods alt var første rigtige møde med CSS Grid.</p>
                            <p>Det hele endte med at vi omkring middagstid den sidste dag, besluttede at nu måtte vi bare lave det som det bedst kunne komme til at se ud. Det kom til at betyde at det tænkte layout blev tilsidesat, og alle sider endte med stort set samme opsætning.</p>
                        <a href="img/socksm.png" target="_blank">
                        <img class="scalepic30m" src="img/socksm.png" alt="This socks"></a>
                            <p>Det er ikke det smukkeste resultat der kom ud af det, men det var lærerigt, og vi havde trods alt meget sjov og fornøjelse i processen, og Bent var der altid til at trøste når det så sortest ud.</p>
                            
                        </div>
                    <hr class="line">
                        
                    <div class="clearfix">
                            <p>Kan du ikke modstå fristelsen til at se det færdige resultet, så tryk på Biotex Ultimate Color og få dig en på opleveren.</p>
                        <a target="blank" href="http://soer64b9.web.eadania.dk/Biotex-igen-igen/"> <img class="scalepic30m" src="img/uclogo.png" alt="Biotex Ultimate Color"></a>
                        </div>
                        </section>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </section>
            </li>
        </ul>
    </main>
