<header class="masterhead">

<!-- Burgermenu -->
<nav>
    <div class="dropdown">
        <div onclick="myFunction()" class="dropbtn">
                    <span ></span>
                    <span></span>
                    <span></span>
    </div>
    
<!-- Menu indhold -->
    <div id="myDropdown" class="dropdown-content">
        
            <ul>
                    <li class="menu"><a href="http://gert3987.web.eadania.dk/eksamen/">Home</a>
                    <a href="web.php">Webudvikling</a>
                    <a href="kommunikation.php">Kommunikation</a>
                    <a href="design.php">Design</a>
                    <a href="dthinking.php">Design thinking</a>
                    <a href="onep.php">One page projekt</a>
                    <a href="andet.php">Alt det andet</a>
                    <a href="refl.php">Reflektioner</a></li>
            </ul>
    </div>
</div>           
</nav>
        
	</header>