<!-- Denne side er udarbejdet af Gert Jørgensen som eksamensprojekt i forbindelse med  1. semesters afslutning af uddannelsen til multimediedesigner på Erhvervsakademi Dania i Skive 2018. -->

<main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subrefl" id="refl">
                    <section class="subkort">
                        <section class="billedtekst">
                            <h2 class="billedtekst-titel">Reflektioner</h2>
                    <div class="clearfix">
                        <img class="scalepic30l" src="img/reflektioner.jpg" alt="Reflektioner">
							<p>Jeg vil her forsøge at give udtryk for processen igennem dette eksamensprojekt.</p>
                            <p>Allerede inden vi havde fået den endelige projektbeskrivelse, var der taget initiativ til en studiegruppe med henblik på deling af notater mv. Her var vi nogle stykker som mødtes på skolen, og fik lavet hver vores notater til den tekst der senere skulle danne basen for vores portefolio.</p>
                            <p>Jeg var meget spændt på hvordan det skulle komme til at gå med opbygningen af en så omfattende side som jeg så en læringportefolio ville kunne udvikle sig til. Jeg gjorde mig nogle tanker om hvordan siden skulle opbygges, jeg var ikke i tvivl om at jeg ville skulle anvende CSS Grid til at styre tekst og billeder.</p>
                            <p>Det første jeg gerne ville have på plads var en menu til navigation på side, jeg downloadede flere forskellige, bland andet fra W3s hjemmeside, man da jeg gerne ville have noget der adskilte sig fra den jeg blev klar over flere andre benyttede, fik jeg en anden i gang. Det viste sig dog ret hurtige at den burgermenu der var ikke kunne swipes, så når det nederste af menuen ikke var synligt var den jo umulig at anvende.</p> 
                            <p>Der ville helt sikkert have kunnet findes en løsning på det problem, jeg anså bare at der ville gå alt for lang tid med det, så jeg endte med selv at lave min burger til en menu, selve menuen fandt jeg i en instruktionsvideo på Lynda, derfra kunne jeg copy/paste den del jeg havde brug for, inkl. noget javascript som var nødvendigt. Det lykkedes at få det sat sammen til en funktionel menu, som siden er blevet tilrettet yderligere så den opfylder det behov jeg mener der er.</p>
                            </div>
                    <div class="clearfix">
                        <a href="img/github.png" target="_blank">
				        <img class="scalepic30r" src="img/github.png" alt="Billede af min GitHub"></a>
                            <p>Efter de første dage at have tumlet med menuen så den nu endelig ud til at fungere, jeg havde indtil da selv lavet backup af mine filer i en ekstern mappe, men jeg kunne godt se at det ikke ville være til at styre i længden, så jeg fik sat mig lidt ind i anvendelsen af GitHub, og har brugt det siden, det har givet en ro at jeg trods alt kunne gå tilbage til en tidligere version, såfremt det hele skulle blive håbløst.</p>
                            <p>Jeg ville lyve hvis jeg sagde at der ikke har været tidspunkter i forløbet hvor jeg har haft mest lyst til, at glemme hele projektet og sige det var bare ærgerligt, det kunne du ikke finde ud af gamle dreng. På den anden side kender jeg jo også mig selv godt nok til at vide, at sådan spiller klaveret ikke, stædighed og tålmodighed er noget der i den grad har været behov for i de seneste uger.</p>
                            <p>Der er ingen tvivl om at Css Grid er et fantastisk stykke værktøj, men hvor kan det dog også give anledning til frustrationer, bedst som man tror der er styr på det, ligner siden pludselig noget man tror er løgn, skammeligt nok må jeg jo indrømme, at der ikke en eneste gang har været tale om andet end en fejl 40.</p>
                            <p>Jeg er trods alt kommet i mål med at opbygge en side fra bunden, og alene det har man vel lov at være lidt stolt af, det er ikke sikkert det indeholder alt, men jeg har taget det med jeg synes er det væsentligste (læs: det jeg kan huske). Jeg skal være den første til at indrømme, at det med at tage notater ikke er en spidskompetence, derfor er jeg ikke i tvivl om at der mangler noget.</p>
                            <p>Jeg kan ikke sige andet end 1. semester har været særdeles lærerigt, og en øjenåbner i forhold til hvor mange ting der bør/skal tages hensyn og stilling til i forbindelse med webdesign.</p>
                            <p>Farven til menuen på denne side er måske ikke den mest maskuline, men den er valgt med fuldt overlæg idet farvekoden er hentet fra min skjorte.</p>
                            <p>Ellers har jeg valgt at holde det så simpelt som muligt, da jeg i erkendelse af egne evner på nuværende tidspunkt, ville kunne komme til at sætte mig under unødigt tidspres såfremt jeg skulle bruge meget tid på at gå ned i alle detaljer. Jeg vil trods alt hellere aflevere en fungerende side, end noget der ikke er gjort færdigt.</p>                       
                            <p>Det har også givet megen læring at skulle kæmpe med både HTML og CSS, jeg har mange gange måtte ty til hjælp på nettet for at finde løsning på et problem, og der er ingen tvivl om at det også vil blive nødvendigt fremover.</p>
                            <p>Den største udfordring der har været var med teksterne, under opbygningen af mit grid fandt jeg en stump kode som jeg mente var den helt rigtige, desværre opdagede jeg for sent at det gav nogle begrænsninger i forhold til de forskellige skærmstørrelser, enten var der meget lidt tekst ved siden af billedet, eller også var der alt for meget. Løsningen blev at der gik et par dage med at få det hele rettet ind på en ny måde. Så kan det godt være der faktisk er noget kode som ikke har nogen effekt, men det der ikke været tid til at tjekke op på og rette, hovedsagen for mig er i første  omgang at siden fungerer og er responsiv.</p>
                            <p>Det har været en ordentlig omgang at komme igennem, bedst som man tror at nu er det hele ved at være på plads, skal der lige rette et par småting, og så griber det om sig. Men på et eller andet tidspunkt kommer man til et punkt hvor sømmet skal slås i.
                            <p>Som den forhåbentligt sidste udfordring, fik jeg slettet min FTP adgang til serveren, heldigvis havde jeg koden på min computer, og i stedet for at tage på akademiet har jeg brugt et eget domæne til at uploade til, så det var muligt at kontrollere alt fungerede som tiltænkt.</p>                       
                            <p>Der kom på grund af de ret omfattende ændringer der blev nødvendigt, en del tidspres her mod slutningen af projektet. Det har medført at alle de fine kommentarer jeg havde en forestilling om skulle skrives ind, ikke rigtig er nået at komme med.</p>
                            <p>De sidste tilretninger er lavet, der kunne selvfølgelig altid finpudses, det er der dog ikke tid til, nu gælder det sidste klargøring til aflevering, og så bliver det spændende at se om bukserøven holder. Og så bliver det skønt med nogle dage hvor der uden tvivl ikke står HTML og CSS på programmet.</p>
                    </div>
                        </section>                        
                        
                        <section class=tiltop>
                            <a href="#">Til toppen</a>
                        </section>
                    </section>
            </li>
        </ul>
    </main>
