    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subrefl" id="refl">
                <a href="#">
                    <figure class="subkort">
                        <img class="subreflpic" src="img/reflektioner.jpg" alt="Reflektioner">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Reflektioner</h2>
							<p>Her vi jeg forsøge at give udtryk for processen igennem dette eksamensprojekt.</p>
                            <p>Allerede inden vi havde fået den endelige projekt beskrivelse, var der taget initiativ til en studiegruppe med henblik på deling af notater mv. Her var vi nogle stykker som mødtes på skolen, og fik lavet hver vores notater til den tekst der senere skulle danne basen for vores portefolio.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2"  id="tekst1">
                            <p>Jeg var meget spændt på hvordan det skulle komme til at gå med opbygningen af en så omfattende side som jeg så en læringportefolio ville kunne udvikle sig til. Jeg gjorde mig nogle tanker om hvordan siden skulle opbygges, jeg var ikke i tvivl om at jeg ville skulle anvende CSS Grid til at styre tekst og billeder.</p>
                            <p>Det første jeg gerne vile have på plads var en menu til navigation på side, jeg downloadede flere forskellige, bland andet fra W3s hjemmeside, man da jeg gerne ville have noget der adskildte sig fra den jeg blev klar over flere andre benyttede, fik jeg en anden igang. Det viste sig dog ret hurtige at den burgemenu der var ikke kunne swipes, så når det nederste af menuen ikke var synligt var den jo umulig at anvende.</p> 
                            <p>Der ville helt sikkert have kunnet findes en løsning på det problem, jeg anså bare at der ville gå alt for lang tid med det, så jeg andte med selv at lave min burger til en menu, selve menuen fandt jeg i en instruktionsvideo på Lynda, derfra kunne jeg copy/paste den del jeg havde brug for, incl noget javascript som var nødvendigt. Det lykkedes at få det sat sammen til en funktionel menu, som siden er blevet tilrette yderligere så den opfylder det behov jeg mener der er.</p>
                    <div class="clearfix">
				        <img class="scalepic30r" src="img/github.png" alt="Billede af min GitHub">
                            <p>Efter de første dage at have tumlet med menuen så den nu endelig ud til at fungere, jeg havde indtil da selv lavet backup af mine filer i en ekstern mappe, men jeg kunne godt se at det ikke ville være til at styre i længden, så jeg fik sat mig ind i navendelsen af GitHub, og har brugt det siden, det har givet en ro at jeg trods alt kunne gå tilbage til en tidligere version, såfremt det hele skulle blive håbløst.</p>
                            <p>Jeg ville lyve hvis jeg sagde at der ikke har været tidspunkter i forløbet hvor jeg har haft mest lyst til, at glemme hele projektet og sige det var bare ærgeligt, det kunne du ikke finde ud af gamle dreng. På den ande side kender jeg jo også mig selv godt nok til at vide, at sådan spiller klaveret ikke, stædighed og tålmodighed er noget der i den grad har været behov for i de seneste uger.</p>
                            <p>Der er ingen tvivl om at Css Grid er et fantastisk stykke værktøj, men hvor kan det dog også give anledning til frustrationer, bedst som man tror der er styr på det, ligner siden pludselig noget man tror er løgn, skammeligt nok må jeg jo indrømme, at der ikke en eneste gang har været tale om andet end en fejl 40.</p>
                            <p>Jeg er trods alt kommet i mål med at opbygge en side fra bunden, og alene det har man vel lov at være lidt stolt af, det er ikke sikkert det indeholder alt, men jeg har taget det med jeg synes er det væsentligste (læs: det jeg kan huske). Jeg skal være den føste til at indrømme, at det med at tage notater ikke er en spidskompetence, derfor er jeg ikke i tvivl om at der mangler noget.</p>
                            <p>Jeg kan ikke sige andet end 1. semester har været særdelse lærerigt, og en øjenåbner i forhold til hvor mange ting der bør/skal tages hensy og stilling til i forbindelse med webdesign.</p>
                            <p>Farven til menuen på denne side er måske ikke den mest maskuline, men den er valgt med fuldt overlæg idet farvekoden er hentet fra min skjorte.</p>
                            <p>Ellers har jeg valgt at holde det så simpelt som muligt, da jeg i erkendelse af egne evner på nuværende tidspunkt, ville kunne komme til at sætte mig under unødigt tidspres såfremt jeg skulle bruge meget tid på at ned i alle detaljer. Jeg vil trods alt hellere aflevere en fungerende side, end noget der ikke er gjort færdigt.</p>                       
                            <p>Det har også givet megen læring at skulle kæmpe med både HTML og CSS, jeg har mange gange måtte ty til hjælp på nettet for at finde løsning på et problem, og der er ingen tvivl om at det vil også blive nødvendigt fremover.</p>                       
                            <p>Der er også ting jeg har fundet min egen løsning på, jeg er ret sikker på at det kunne gøres smartere og anderledes, men igen er jeg overbevist om at jeg ville bruge uforholdsmæssigt meget tid på at finde løsningen i forhold til det der blev løsningen.</p>
                            <p>Den støreste ting jeg har lavet en ikke helt optimal løsning på, er teksterne, under opbygningen mit grid fandt jeg en stump kode som jeg mente var den helt rigtige, desværre opdagede jeg for sent at det gav nogle begrænsninger i forhol til de forskellige skærmstørrelser, enten var der meget lidt tekst ved siden af billedet, eller også var der alt for lidt billede. Løsningen blev at jeg har sat teksterne ind dobbelt, så jeg kan styre hvilken teksdel der skal bruges hvor. Det er jeg udemærket klar over ikke er særligt hensigtsmæssigt men det fungerer og var på tidspunktet den hurtige løsning jeg lige kunne finde på.</p>
                            <p>I skrivende stund mangler jeg nu blot at få gået det hele igennem så det står sakrpt, der kommer nok lidt små tilretninger, men det store træk er overstået, og så må jeg bare se om bukserøven holder.</p>
                    </div>
                        </figcaption>
                    </figure>
                </a>
            </li>
        </ul>
    </main>
