<header class="masterhead">

<!-- Burgermenu -->
<nav>
    <div class="dropdown">
        <div onclick="myFunction()" class="dropbtn">
                    <span ></span>
                    <span></span>
                    <span></span>
    </div>
    
<!-- Menu indhold -->
    <div id="myDropdown" class="dropdown-content">
        <h1>
            <ul>
                <li><a href="http://gert3987.web.eadania.dk/eksamen/">Home</a></li>
            </ul>
        </h1>
    </div>
</div>           
</nav>
        
	</header>