    <main id="content" class="main-area">
        <ul class="subindex">
            <li class="subkort-emne subhtml" id="html">
                <a href="#">
                    <figure class="subkort">
                        <img class="subhtmlpic" src="img/html_logo.png" alt="Noget om HTML">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">HTML</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        
                        <figcaption class="billedtekst2">
                    <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subcss" id="css">
                <a href="#">
                    <figure class="subkort">
                        <img class="subcsspic" src="img/css3_logo.png" alt="Noget om CSS.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">CSS</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
           </li>
            
            <li class="subkort-emne subserver" id="server">
                <a href="#">
                    <figure class="subkort">
                        <img class="subserverpic" src="img/server.png" alt="Servere.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Servere</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subhistorie" id="historie">
                <a href="#">
                    <figure class="subkort">
                        <img class="subhistoriepic" src="img/www.jpg" alt="Internettets historie">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Historie</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subgrid" id="grid">
                <a href="#">
                    <figure class="subkort">
                        <img class="subgridpic" src="img/css_grid.png" alt="CSS Grid.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">CSS Grid</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subversion" id="version">
                <a href="#">
                    <figure class="subkort">
                        <img class="subversionpic" src="img/git_logo.jpg" alt="Versionsstyring.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Versionsstyring</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
            
            <li class="subkort-emne subarkitektur" id="arkitektur">
                <a href="#">
                    <figure class="subkort">
                        <img class="subarkitekturpic" src="img/information.jpg" alt="Informationsarkitektur.">
                        <figcaption class="billedtekst">
                            <h2 class="billedtekst-titel">Informationsarkitektur</h2>
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                        <figcaption class="billedtekst2">
							<p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                            <p>Her kommer tekst mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle mumle.</p>
                        </figcaption>
                    </figure>
                </a>
            </li>
        </ul>
    </main>
