<header class="masterhead">

<!-- Burgermenu -->
<nav>
    <div class="dropdown">
        <div onclick="myFunction()" class="dropbtn">
                    <span ></span>
                    <span></span>
                    <span></span>
    </div>
    
<!-- Menu indhold -->
    <div id="myDropdown" class="dropdown-content">
        <h1>
            <ul>
                <ul>
                    <li class="menu"><a href="http://gert3987.web.eadania.dk/eksamen/">Home</a>
                    <a href="web.php">Webudvikling</a>
                    <a href="kommunikation.php">Kommunikation</a>
                    <a href="design.php">Design</a>
                    <a href="dthinking.php">Design thinking</a>
                    <a href="onep.php">One page projekt</a>
                    <a href="andet.php">Alt det andet</a>
                    <a href="refl.php">Reflektioner</a></li>
                </ul>
                    <hr>
                <ul>
                    <li class="menu"><a href="#html">HTML</a>
                    <a href="#css">CSS</a>
                    <a href="#server">Server</a>
                    <a href="#historie">Internettets historie</a>
                    <a href="#grid">CSS Grid</a>
                    <a href="#version">Versionsstyring</a>
                    <a href="#arkitektur">Informationsarkitektur</a></li>
                </ul>
            </ul>
        </h1>
    </div>
</div>           
</nav>        
	</header>

