<header class="masterhead">

<!-- Burgermenu -->
<nav>
    <div class="dropdown">
        <div onclick="myFunction()" class="dropbtn">
                    <span ></span>
                    <span></span>
                    <span></span>
    </div>
    
<!-- Menu indhold -->
    <div id="myDropdown" class="dropdown-content">
        <h1>
            <ul>
                <li><a href="http://gert3987.web.eadania.dk/eksamen/">Home</a></li>
                <li><a href="#html">HTML</a></li>
                <li><a href="#css">CSS</a></li>
                <li><a href="#server">Server</a></li>
                <li><a href="#historie">Internettets historie</a></li>
                <li><a href="#grid">CSS Grid</a></li>
                <li><a href="#version">Versionsstyring</a></li>
                <li><a href="#arkitektur">Informationsarkitektur</a></li>
            </ul>
        </h1>
    </div>
</div>           
</nav>        
	</header>

